### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Aaronek10** [DimensionalDevelopment/DimDoors#192]
[15:56:31] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
java.lang.NullPointerException: null
	at net.minecraft.server.management.PlayerChunkMap.handler$removePlayerWithViews$zzf000(SourceFile:569) ~[ou.class:?]
	at net.minecraft.server.management.PlayerChunkMap.func_72695_c(SourceFile) ~[ou.class:?]
	at net.minecraft.server.management.PlayerList.func_72367_e(PlayerList.java:414) ~[pl.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147231_a(NetHandlerPlayServer.java:853) ~[pa.class:?]
	at net.minecraft.network.NetworkManager.func_179293_l(NetworkManager.java:453) ~[gw.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:213) ~[oz.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]

**Comment by BoogieMonster1O1** [comment]
does it happen without dimdoors? it doesnt really look like dimdoors is involved in the stacktrace 🤔

**Comment by Aaronek10** [comment]
With dimdoors, this happends only when trying to enter any dungeon or dimension

**Comment by Aaronek10** [comment]
without dimdoors, everything works fine

**Comment by BoogieMonster1O1** [comment]
> With dimdoors, this happends only when trying to enter any dungeon or dimension

can you send a list of mods you have? and the full latest.log?

**Comment by Aaronek10** [comment]
![image](https://user-images.githubusercontent.com/37957871/112862147-c267e080-90b5-11eb-92a0-387444929988.png)
This all mods on server
latest.log is currently unobtainable while server is running right now without it and my friends are doing something right now 😕 
i can try later to reproduce crash with more extented log

**Comment by BoogieMonster1O1** [comment]
This is caused by the betterportals mod. After some googling it seems to happen with galacticraft as well.
remove it, that should hopefully fix the issues.

**Comment by BoogieMonster1O1** [comment]
relates to #130

**Comment by Aaronek10** [comment]
Okey, thanks!
