### ISSUE TITLE
Crashes with ExtraDoors

### ISSUE THREAD

**Issue by DarkShadow44** [DimensionalDevelopment/DimDoors#197]
Source of mod: https://github.com/ExtraCrafTX/ExtraDoors
Attaching modified version of mod for usage with 1.17-SNAPSHOT.

PS: Don't try to use purpur door, it will crash. Glass door works fine though.

```
---- Minecraft Crash Report ----
// Why is it breaking :(

Time: 4/25/21 3:06 PM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'dimdoors'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
	at net.minecraft.class_310.<init>(class_310.java:442)
	at net.minecraft.client.main.Main.main(Main.java:179)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: java.lang.RuntimeException: Attempted to register ID ResourceKey[minecraft:block / dimdoors:block_ag_dim_gold_door] at different raw IDs (986, 1016)! If you're trying to override an item, use .set(), not .register()!
	at net.minecraft.class_2370.handler$zef000$setPre(class_2370.java:650)
	at net.minecraft.class_2370.method_31051(class_2370.java)
	at net.minecraft.class_2370.method_10273(class_2370.java:72)
	at net.minecraft.class_2348.method_10273(class_2348.java:28)
	at net.minecraft.class_2370.method_10272(class_2370.java:103)
	at net.minecraft.class_2378.method_10230(class_2378.java:430)
	at org.dimdev.dimdoors.block.door.DimensionalDoorBlockRegistrar.register(DimensionalDoorBlockRegistrar.java:62)
	at org.dimdev.dimdoors.block.door.DimensionalDoorBlockRegistrar.handleEntry(DimensionalDoorBlockRegistrar.java:53)
	at org.dimdev.dimdoors.block.door.DimensionalDoorBlockRegistrar.lambda$init$0(DimensionalDoorBlockRegistrar.java:47)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.dimdev.dimdoors.block.door.DimensionalDoorBlockRegistrar.init(DimensionalDoorBlockRegistrar.java:47)
	at org.dimdev.dimdoors.block.door.DimensionalDoorBlockRegistrar.<init>(DimensionalDoorBlockRegistrar.java:41)
	at org.dimdev.dimdoors.DimensionalDoorsInitializer.onInitialize(DimensionalDoorsInitializer.java:133)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	... 11 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
	at net.minecraft.class_310.<init>(class_310.java:442)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:179)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- System Details --
Details:
	Minecraft Version: 21w14a
	Minecraft Version ID: 21w14a
	Operating System: Linux (amd64) version 5.11.16-arch1-1
	Java Version: 1.8.0_202, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1625539968 bytes (1550 MB) / 2113929216 bytes (2016 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 16
	JVM Flags: 8 total; -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		autoconfig1u: Auto Config v1 Updated 3.3.1
		cardinal-components-base: Cardinal Components API (base) 3.0.0-nightly.21w14a
		cardinal-components-chunk: Cardinal Components API (chunks) 3.0.0-nightly.21w14a
		cardinal-components-entity: Cardinal Components API (entities) 3.0.0-nightly.21w14a
		cardinal-components-item: Cardinal Components API (items) 3.0.0-nightly.21w14a
		cardinal-components-level: Cardinal Components API (world saves) 3.0.0-nightly.21w14a
		cardinal-components-util: Cardinal Components API (utilities) 3.0.0-nightly.21w14a
		cardinal-components-world: Cardinal Components API (worlds) 3.0.0-nightly.21w14a
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v4 5.0.16
		com_flowpowered_flow-math: flow-math 1.0.3
		com_github_dimensionaldevelopment_poly2tri_java: poly2tri.java 0.1.1
		dimdoors: DimensionalDoors 4.0.0+beta.2-25.04.2021
		extradoors: ExtraDoors 1.8.2-1.16.2
		fabric: Fabric API 0.32.7+1.17
		fabric-api-base: Fabric API Base 0.2.2+23b3c92e17
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.0.2+413ddf6417
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.8+413ddf6417
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+92519afa17
		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+bb68760017
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa17
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+41a6855217
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.2+23b3c92e17
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+92519afa17
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.9+413ddf6417
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.3+92519afa17
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.8+d748de6c17
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa17
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+92519afa17
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+23b3c92e17
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.6+23b3c92e17
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+524a2e8517
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e17
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+23b3c92e17
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+92519afa17
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa17
		fabric-models-v0: Fabric Models (v0) 0.2.1+92519afa17
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.7+413ddf6417
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+413ddf6417
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa17
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.5+40e100eb17
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+92519afa17
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+92519afa17
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.8+413ddf6417
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.1+92519afa17
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+413ddf6417
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.1.0+2a1dabb617
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+92519afa17
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+92519afa17
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+92519afa17
		fabric-rendering-v1: Fabric Rendering (v1) 1.5.2+41a6855217
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.5+23b3c92e17
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.1+41a6855217
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+23b3c92e17
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.8+23b3c92e17
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.3+41a6855217
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+92519afa17
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.9+36b77c3e17
		fabricloader: Fabric Loader 0.11.3
		jankson: Jankson 3.0.1+j1.2.0
		java: Java HotSpot(TM) 64-Bit Server VM 8
		libgui: LibGui 4.0.0-alpha.1+21w11a
		matrix: Matrix 1.0.0
		minecraft: Minecraft 1.17-alpha.21.14.a
		org_jgrapht_jgrapht-core: jgrapht-core 1.1.0
		programmerartinjector: Programmer Art Injector 1.2.1
		seedy-behavior: Seedy Behavior 1.0.1
	Launched Version: fabric-loader-0.11.3-21w14a
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NO CONTEXT
	GL Caps: Using framebuffer using OpenGL 3.2
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>
```

**Comment by DarkShadow44** [comment]
Sorry, attachment failed.

[ExtraDoors-1.8.2-1.16.2.zip](https://github.com/DimensionalDevelopment/DimDoors/files/6371993/ExtraDoors-1.8.2-1.16.2.zip)

Download and rename to .jar

**Comment by micahflack** [comment]
The same incompatibility exists with GlassDoors 1.5.0-1.17.

**Comment by CreepyCre** [comment]
I just tested GlassDoors 1.5.0-1.17 with Dimensional Doors in my dev environment and was not able to reproduce the issue. It seems to me as though you are not using the most recent release of Dimensional Doors.

**Comment by micahflack** [comment]
My bad. Looked at it again and there was a mixup with the mods I had loaded. Similar but separate issue that was resolved elsewhere.
