### ISSUE TITLE
[1.17] Multiplayer Server Crashes on Startup

### ISSUE THREAD

**Issue by kalinzange** [DimensionalDevelopment/DimDoors#213]
Minecraft Version: 1.17 (JAVA Edition)
Fabric Version: 0.36.0
Mod Version: [1.17] Dimensional Doors 4.0.0+beta.2-11.06.2021

[latest.log](https://github.com/DimensionalDevelopment/DimDoors/files/6728265/latest.log)
[console.log](https://github.com/DimensionalDevelopment/DimDoors/files/6728266/console.log)

```
[18:39:42] [main/INFO]: Smooth Boot config initialized
Exception in thread "main" java.lang.RuntimeException: Failed to setup Fabric server environment!
        at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:58)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: An exception occurred when launching the server!
        at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:116)
        at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:56)
Caused by: java.lang.RuntimeException: An exception occurred when launching the server!
        at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:70)
        at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:114)
        ... 1 more
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:68)
        ... 2 more
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:236)
        at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
        at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:28)
        ... 7 more
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
        ... 9 more
Caused by: java.lang.NoClassDefFoundError: net/fabricmc/fabric/api/client/render/fluid/v1/FluidRenderHandler
        at org.dimdev.dimdoors.block.EternalFluidBlock.<init>(EternalFluidBlock.java:25)
        at org.dimdev.dimdoors.block.ModBlocks.<clinit>(ModBlocks.java:154)
        at org.dimdev.dimdoors.world.feature.ModFeatures.<clinit>(ModFeatures.java:48)
        at net.minecraft.class_3864.handler$bbg000$addGateway(class_3864.java:589)
        at net.minecraft.class_3864.method_17003(class_3864.java:57)
        at net.minecraft.class_5478.method_30698(class_5478.java:333)
        at net.minecraft.class_5504.<clinit>(class_5504.java:19)
        at net.minecraft.class_5458.method_30567(class_5458.java:52)
        at net.minecraft.class_5458.method_30566(class_5458.java:75)
        at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:723)
        at net.minecraft.class_5458.<clinit>(class_5458.java:74)
        at net.minecraft.class_2378.<clinit>(class_2378.java:266)
        at net.minecraft.class_2966.method_12851(class_2966.java:44)
        at net.minecraft.server.Main.main(Main.java:92)
        ... 14 more
Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.api.client.render.fluid.v1.FluidRenderHandler
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
        at net.fabricmc.loader.launch.server.InjectingURLClassLoader.loadClass(InjectingURLClassLoader.java:57)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
        at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:175)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
        ... 28 more
```

**Comment by CreepyCre** [comment]
Short question:
Is this from the most recent curseforge release or built from dev?
I believe this should be fixed in dev. We are currently doing a bit of cleanup and bug fixing but we should be getting ready for a new (and hopefully mostly bug free) release soon-ish.

**Comment by kalinzange** [comment]
Hiya,

> Is this from the most recent curseforge release or built from dev?

https://www.curseforge.com/minecraft/mc-mods/dimensionaldoors/files/3348806
This was tagged as Beta, so I believe Built from dev?

> I believe this should be fixed in dev. We are currently doing a bit of cleanup and bug fixing but we should be getting ready for a new (and hopefully mostly bug free) release soon-ish.

Sounds good! Once it's fixed please close this Issue so I can update and provide feedback on further issues.

**Comment by CreepyCre** [comment]
> https://www.curseforge.com/minecraft/mc-mods/dimensionaldoors/files/3348806
> This was tagged as Beta, so I believe Built from dev?

This beta build is around one month old. If you want to test on one of the dev builds you can swing by the Discord, someone will probably be willing to send you a recent dev build. Alternatively you can build it yourself.

**Comment by kalinzange** [comment]
Hiya,

So Updates & Feedback:

- No Crashes on Multiplayer Server when startup
- No Crashes on the Client Side

- When entering on the Oak Dimensional Door and when I open again the door to leave, I get the following achievement (not sure if this is intended - although I found some chests on the dimension)

![image](https://user-images.githubusercontent.com/38161086/124763498-f01dba80-df2b-11eb-878a-6a1b7d73cc86.png)

- ~~You cannot exit from the same Oak Dimensional Door, neither from the Iron Ones and also I can't be killed on the Void (Can't use the /kill Command either - doesn't kill me actually)~~, Seems you actually can but I had to try like 5x to do it or wait long enough even sometimes I had to leave the server and join to fully exit through the door

Server Console Shows some `Could not serialize org.dimdev.dimdoors.command.arguments.EnumArgumentType` as well `ignored dubious move packet dimdoors:personal_pockets` (Full Server & Client Console at the Bottom of this Comment)

Quick Question: How long does this effect is active?
![image](https://user-images.githubusercontent.com/38161086/124766325-bb5f3280-df2e-11eb-8a78-62288c6fcf3a.png)

[latest-client.log](https://github.com/DimensionalDevelopment/DimDoors/files/6777396/latest.log)
[latest-server.log](https://github.com/DimensionalDevelopment/DimDoors/files/6777400/latest.log)

Anything additionally you would like me to test let me know

**Comment by kalinzange** [comment]
Hello,

I've added a couple more mods to my server and invited one of my friends to play Minecraft. The dimensions started to bug out:

 - Quartz Dimension Door once entered you couldn't exit, everything was white around 
 - Didn't Test Gold & Wooden since the server started to crash and decided to remove the mod to prevent further crashes

Both Server Console Logs & Server Crash Reports Attached
 
[crash-2021-07-13_22.50.36-server.txt](https://github.com/DimensionalDevelopment/DimDoors/files/6812229/crash-2021-07-13_22.50.36-server.txt)
[latest-DimDoors2.log](https://github.com/DimensionalDevelopment/DimDoors/files/6812230/latest-DimDoors2.log)
[latest-DimBugs.log](https://github.com/DimensionalDevelopment/DimDoors/files/6812231/latest-DimBugs.log)
[crash-2021-07-13_22.56.45-server.txt](https://github.com/DimensionalDevelopment/DimDoors/files/6812232/crash-2021-07-13_22.56.45-server.txt)

**Comment by noi2coco** [comment]
#219 fixes the Lost and found achievement triggering when a door is opened/closed
