### ISSUE TITLE
Error while Generating Pocket Dimensions

### ISSUE THREAD

**Issue by spencers145** [DimensionalDevelopment/DimDoors#229]
[29.08 18:30:24] [Server] java.lang.NullPointerExceptionCannot invoke "net.minecraft.class_3218.method_27983()" because the return value of "org.dimdev.dimdoors.pockets.PocketGenerationContext.getWorld()" is null
[29.08 18:30:24] [Server] 	at org.dimdev.dimdoors.pockets.generator.VoidGenerator.prepareAndPlacePocket(VoidGenerator.java:29) ~[DimensionalDoors-4.0.0+beta.3-26.07.2021.jar:?]
[29.08 18:30:24] [Server] 	at org.dimdev.dimdoors.pockets.virtual.reference.PocketGeneratorReference.prepareAndPlacePocket(PocketGeneratorReference.java:137) ~[DimensionalDoors-4.0.0+beta.3-26.07.2021.jar:?]
[29.08 18:30:24] [Server] 	at org.dimdev.dimdoors.pockets.PocketGenerator.generatePocketV2(PocketGenerator.java:54) ~[DimensionalDoors-4.0.0+beta.3-26.07.2021.jar:?]
[29.08 18:30:24] [Server] 	at org.dimdev.dimdoors.pockets.PocketGenerator.generateFromPocketGroupV2(PocketGenerator.java:50) ~[DimensionalDoors-4.0.0+beta.3-26.07.2021.jar:?]
[29.08 18:30:24] [Server] 	at org.dimdev.dimdoors.pockets.PocketGenerator.generatePublicPocketV2(PocketGenerator.java:45) ~[DimensionalDoors-4.0.0+beta.3-26.07.2021.jar:?]
[29.08 18:30:24] [Server] 	at org.dimdev.dimdoors.rift.targets.PublicPocketTarget.makeLinkTarget(PublicPocketTarget.java:36) ~[DimensionalDoors-4.0.0+beta.3-26.07.2021.jar:?]
[29.08 18:30:24] [Server] 	at org.dimdev.dimdoors.rift.targets.RestoringTarget.receiveOther(RestoringTarget.java:17) ~[DimensionalDoors-4.0.0+beta.3-26.07.2021.jar:?]
[29.08 18:30:24] [Server] 	at org.dimdev.dimdoors.api.rift.target.Target.as(Target.java:16) ~[DimensionalDoors-4.0.0+beta.3-26.07.2021.jar:?]
[29.08 18:30:24] [Server] 	at org.dimdev.dimdoors.block.entity.RiftBlockEntity.teleport(RiftBlockEntity.java:192) ~[DimensionalDoors-4.0.0+beta.3-26.07.2021.jar:?]
[29.08 18:30:24] [Server] 	at org.dimdev.dimdoors.block.entity.EntranceRiftBlockEntity.innerTeleport(EntranceRiftBlockEntity.java:89) ~[DimensionalDoors-4.0.0+beta.3-26.07.2021.jar:?]
[29.08 18:30:24] [Server] 	at org.dimdev.dimdoors.block.entity.EntranceRiftBlockEntity.teleport(EntranceRiftBlockEntity.java:85) ~[DimensionalDoors-4.0.0+beta.3-26.07.2021.jar:?]
[29.08 18:30:24] [Server] 	at org.dimdev.dimdoors.block.door.DimensionalDoorBlock.onCollision(DimensionalDoorBlock.java:80) ~[DimensionalDoors-4.0.0+beta.3-26.07.2021.jar:?]
[29.08 18:30:24] [Server] 	at org.dimdev.dimdoors.block.door.DimensionalDoorBlock.onAfterMovePlayerCollision(DimensionalDoorBlock.java:64) ~[DimensionalDoors-4.0.0+beta.3-26.07.2021.jar:?]
[29.08 18:30:24] [Server] 	at net.minecraft.class_3244.handler$zzh000$checkBlockCollision(class_3244.java:2649) ~[intermediary-server.jar:?]
[29.08 18:30:24] [Server] 	at net.minecraft.class_3244.method_12063(class_3244.java:943) ~[intermediary-server.jar:?]
[29.08 18:30:24] [Server] 	at net.minecraft.class_2828.method_12272(class_2828.java:114) ~[intermediary-server.jar:?]
[29.08 18:30:24] [Server] 	at net.minecraft.class_2828$class_2830.method_11054(class_2828.java:16) ~[intermediary-server.jar:?]
[29.08 18:30:24] [Server] 	at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-server.jar:?]
[29.08 18:30:24] [Server] 	at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-server.jar:?]
[29.08 18:30:24] [Server] 	at net.minecraft.class_1255.method_18859(class_1255.java:151) ~[intermediary-server.jar:?]
[29.08 18:30:24] [Server] 	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-server.jar:?]
[29.08 18:30:24] [Server] 	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:788) ~[intermediary-server.jar:?]
[29.08 18:30:24] [Server] 	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164) ~[intermediary-server.jar:?]
[29.08 18:30:24] [Server] 	at net.minecraft.class_1255.method_16075(class_1255.java:125) ~[intermediary-server.jar:?]
[29.08 18:30:24] [Server] 	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:770) ~[intermediary-server.jar:?]
[29.08 18:30:24] [Server] 	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:764) ~[intermediary-server.jar:?]
[29.08 18:30:24] [Server] 	at net.minecraft.class_1255.method_18857(class_1255.java:134) ~[intermediary-server.jar:?]
[29.08 18:30:24] [Server] 	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:749) ~[intermediary-server.jar:?]
[29.08 18:30:24] [Server] 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:701) ~[intermediary-server.jar:?]
[29.08 18:30:24] [Server] 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[intermediary-server.jar:?]
[29.08 18:30:24] [Server] 	at java.lang.Thread.run(Thread.java:831) [?:?]

Trying to create any kind of pocket dimension fails, causes an error, and tells us to report the issue. What else do you need to debug this?

**Comment by spencers145** [comment]
Discovered the source of the issue. It's an incompatibility (one that I don't understand) with the Incendium datapack.
