### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by AmonRay** [DimensionalDevelopment/DimDoors#237]
```
Time: 10/4/21, 5:19 PM
Description: Initializing game

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2248.method_9578(net.minecraft.class_1761, net.minecraft.class_2371)" because the return value of "net.minecraft.class_1747.method_7711()" is null
	at net.minecraft.class_1747.method_7850(class_1747.java:202)
	at net.minecraft.class_310.method_1546(class_310.java:775)
	at net.minecraft.class_310.<init>(class_310.java:576)
	at net.minecraft.client.main.Main.main(Main.java:179)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_128.handler$ekh000$fillPatchouliContext(class_128.java:521)

-- Patchouli Book Info --
Details:
	Patchouli open book context: n/a
Stacktrace:
	at net.minecraft.class_128.handler$ekh000$fillPatchouliContext(class_128.java:521)
	at net.minecraft.class_128.<init>(class_128.java:37)
	at net.minecraft.class_128.method_560(class_128.java:267)
	at net.minecraft.client.main.Main.main(Main.java:185)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
```

Using latest version of DimensionalDoors DimensionalDoors-4.0.0+beta.3-27.09.2021.jar

Mine version: 1.17.1
Fabric 0.11.6
Fabric API 0.40.1

Tested with DimensionalDoors-4.0.0+beta.3-26.07.2021.jar - everything works as expected

**Comment by CreepyCre** [comment]
Please use [Not Enough Crashes](https://www.curseforge.com/minecraft/mc-mods/not-enough-crashes) and submit a new crash report. It'll make the crash report actually readable.

**Comment by AmonRay** [comment]
```
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 10/4/21, 10:28 PM
Description: Initializing game

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2248.method_9578(net.minecraft.class_1761, net.minecraft.class_2371)" because the return value of "net.minecraft.class_1747.method_7711()" is null
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.61)
	at net.minecraft.item.BlockItem.appendStacks(BlockItem:202)
	at net.minecraft.client.MinecraftClient.initializeSearchableContainers(MinecraftClient:775)
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient:576)
	at net.minecraft.client.main.Main.main(Main:179)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_128.handler$elb000$fillPatchouliContext(class_128.java:1521)

-- Patchouli Book Info --
Details:
	Patchouli open book context: n/a
Stacktrace:
	at net.minecraft.class_128.handler$elb000$fillPatchouliContext(class_128.java:1521)
	at net.minecraft.class_128.<init>(class_128.java:37)
	at net.minecraft.class_128.method_560(class_128.java:267)
	at net.minecraft.client.main.Main.main(Main.java:185)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
```

**Comment by triphora** [comment]
Your crash report is truncated, give the whole thing and not just the stacktraces

**Comment by AmonRay** [comment]
```
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 10/4/21, 10:40 PM
Description: Initializing game

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2248.method_9578(net.minecraft.class_1761, net.minecraft.class_2371)" because the return value of "net.minecraft.class_1747.method_7711()" is null
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.61)
	at net.minecraft.item.BlockItem.appendStacks(BlockItem:202)
	at net.minecraft.client.MinecraftClient.initializeSearchableContainers(MinecraftClient:775)
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient:576)
	at net.minecraft.client.main.Main.main(Main:179)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_128.handler$elb000$fillPatchouliContext(class_128.java:1521)

-- Patchouli Book Info --
Details:
	Patchouli open book context: n/a
Stacktrace:
	at net.minecraft.class_128.handler$elb000$fillPatchouliContext(class_128.java:1521)
	at net.minecraft.class_128.<init>(class_128.java:37)
	at net.minecraft.class_128.method_560(class_128.java:267)
	at net.minecraft.client.main.Main.main(Main.java:185)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- Initialization --
Details:

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 532459552 bytes (507 MiB) / 1371537408 bytes (1308 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz
	Identifier: Intel64 Family 6 Model 42 Stepping 7
	Microarchitecture: Sandy Bridge (Client)
	Frequency (GHz): 3.40
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce GTX 1070
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1b81
	Graphics card #0 versionInfo: DriverVersion=30.0.14.7212
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 1.87
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MB): 4096.00
	Memory slot #1 clockSpeed (GHz): 1.87
	Memory slot #1 type: DDR3
	Memory slot #2 capacity (MB): 4096.00
	Memory slot #2 clockSpeed (GHz): 1.87
	Memory slot #2 type: DDR3
	Memory slot #3 capacity (MB): 4096.00
	Memory slot #3 clockSpeed (GHz): 1.87
	Memory slot #3 type: DDR3
	Virtual memory max (MB): 33730.22
	Virtual memory used (MB): 14745.48
	Swap memory total (MB): 17408.00
	Swap memory used (MB): 769.50
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8192m -Xms256m -XX:PermSize=256m
	Fabric Mods: 
		accurateblockplacement: Accurate Block Placement 1.0.10
		adorn: Adorn 2.1.5+1.17.1
		advanced_runtime_resource_pack: Runtime Resource Pack 0.4.3
		adventurez: AdventureZ 1.2.11
		agape_space: Space Dimensions 0.3.2
		amecsapi: Amecs API 1.1.4+mc21w16a
		apoli: Apoli 2.0.0
		appleskin: AppleSkin mc1.17-2.1.3
		appliedenergistics2: Applied Energistics 2 9.0.0-alpha.1
		aqupdgrizzly: Grizzly Bear mob 1.17-1.2.0
		arcanus: Arcanus 1.16
		architectury: Architectury 2.5.30
		artisanat: Artisanat 2.1
		asa: Air Strafing Attribute 1.2
		atmosfera: Atmosfera 2.0.0+mc1.17
		autoconfig1u: Auto Config v1 Updated 3.3.1
		automatone: Automatone 0.4.1
		autopath: Automatic Path 1.4.4
		axesareweapons: Axes Are Weapons 1.3-1.17
		backpackmod: Backpack Mod 1.17-2.0.1
		bclib: BCLib 0.3.1
		bedspreads: Bedspreads 1.4.0-1.17
		betterdungeons: YUNG's Better Dungeons 1.17-1.0.2
		betterend: Better End 0.11.0-pre
		bettermineshafts: YUNG's Better Mineshafts 1.17-1.0.1
		betternether: Better Nether 5.1.3
		betterstrongholds: YUNG's Better Strongholds 1.17-1.1.2
		bewitchment: Bewitchment 1.17-9
		bitsandchisels: BitsAndChisels 2.5.3
		blame: Blame 1.17-4.2.0-fabric
		blockus: Blockus 2.2.10+1.17.1
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.2.3-1.17.1
		calio: Calio 1.0.3
		cardinal-components: Cardinal Components API 3.1.1
		cardinal-components-base: Cardinal Components API (base) 3.1.1
		cardinal-components-block: Cardinal Components API (blocks) 3.1.1
		cardinal-components-chunk: Cardinal Components API (chunks) 3.1.1
		cardinal-components-entity: Cardinal Components API (entities) 3.1.1
		cardinal-components-item: Cardinal Components API (items) 3.1.1
		cardinal-components-level: Cardinal Components API (world saves) 3.1.1
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 3.1.1
		cardinal-components-util: Cardinal Components API (utilities) 3.1.1
		cardinal-components-world: Cardinal Components API (worlds) 3.1.1
		castle_dungeons: Castle Dungeons 2.6-1.17-fabric
		charm: Charm 3.3.2
		chime: Chime 1.2.0-SNAPSHOT
		cloth-api: Cloth API 2.0.54
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 2.0.54
		cloth-common-events-v1: Cloth Common Events v1 2.0.54
		cloth-config2: Cloth Config v5 5.0.38
		cloth-datagen-api-v1: Cloth Datagen v1 2.0.54
		cloth-scissors-api-v1: Cloth Scissors API v1 2.0.54
		cloth-utils-v1: Cloth Utils v1 2.0.54
		clumps: Clumps 7.0.8
		coat: Coat 1.0.0-beta.9
		colorbricks: ColorBricks 1.17.1-1.2.1
		com_electronwill_night-config_core: core 3.6.3
		com_electronwill_night-config_toml: toml 3.6.3
		com_fasterxml_jackson_dataformat_jackson-dataformat-yaml: jackson-dataformat-yaml 2.12.2
		com_flowpowered_flow-math: flow-math 1.0.3
		com_focamacho_sealconfig: sealconfig 1.2.2
		com_github_dimensionaldevelopment_poly2tri_java: poly2tri.java 0.1.1
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		comforts: Comforts 0.0.6-1.17.1
		compress: Compress 'em [1.2]
		conjuring: Conjuring 1.0.7
		cosmetic-armor: Cosmetic Armor 1.1.0
		couplings: Couplings 1.5.0+1.17
		craborigin: A Crab Origin 1.0
		croptopia: Croptopia 1.6.3
		crowdin-translate: CrowdinTranslate 1.3+1.17
		cullleaves: Cull Leaves 2.3.0
		customportalapi: Custom Portal Api 0.0.1-beta41-1.17
		dankstorage: Dank Storage 2.1-1.17.1
		dark-enchanting: Dark Enchanting 0.4.1-1.17.1
		darkness: True Darkness 1.6.74
		dawn: Dawn API 2.0.6
		deerorigin: A Deer Origin 3.0
		dimdoors: DimensionalDoors 4.0.0+beta.3-27.09.2021
		dimores: DimensionalOres 1.0.1
		disable_custom_worlds_advice: Disable Custom Worlds Advice 1.3
		dml-refabricated: Deep Mob Learning: Refabricated 0.4.4-beta
		dml-refabricated-base: DML: Refabricated - Base 0.4.4-beta
		dml-refabricated-events: DML: Refabricated - Vanilla Events 0.4.4-beta
		dml-refabricated-modular-armor: DML: Refabricated - Glitch Armor 0.4.4-beta
		dml-refabricated-rei: DML: Refabricated - REI Integration 0.4.4-beta
		doomangelring: Doom Angel Ring 1.0.1
		dragonloot: DragonLoot 1.0.9
		dst: Don't Starve Origins 1
		dual_riders: DualRiders 1.0.5
		dungeons_arise: When Dungeons Arise 2.1.47-fabric
		ec-core: Essential Commands Core 1.0.0-mc1.17.1
		eldritch_mobs: Eldritch Mobs 1.9.6
		emerald_tools: Emerald Tools 1.2.27
		enchantment_lore: EnchantmentLore 1.2.1+MC1.17.1
		endrem: End Remastered 4.1.0
		enhancedblockentities: Enhanced Block Entities 0.5+1.17
		enhancedcelestials: Enhanced Celestials 2.0.5
		entityculling: EntityCulling-Fabric 1.3.3
		enva: Environmental Armor 1.4.0
		environmentz: EnvironmentZ 1.1.6
		essential_commands: Essential Commands 0.16.2-mc1.17.1
		exotic-art-core: Exotic Art Core Content Pack 1.0.408
		exotic-art-tech: Exotic Art Tech Pack 1.2.408
		exotic-matter: Exotic Matter 2.12.408
		expanded_armor_enchanting: Expanded Armor Enchanting 1.0.1
		expanded_axe_enchanting: Expanded Axe Enchanting 1.0.2
		expanded_trident_enchanting: Expanded Trident Enchanting 1.0.2
		expanded_weapon_enchanting: Expanded Weapon Enchanting 1.0.1
		expcontainer: Experience Container [XP] 1.15.2
		fabric: Fabric API 0.40.1+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b446313
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.0+cbda931818
		fabric-biome-api-v1: Fabric Biome API (v1) 3.2.0+cbda931818
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b446318
		fabric-command-api-v1: Fabric Command API (v1) 1.1.3+5ab9934c18
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa18
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+cbda931818
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.3.0+cbda931818
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da31018
		fabric-diagonal-panes: Fabric Diagonal Panes 0.5.0
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.11+6cefd57718
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.2.3+87cc6e4c18
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.10+fc40aa9d18
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa18
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+cbda931818
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b4463d5
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab612118
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+cbda931818
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e18
		fabric-language-kotlin: Fabric Language Kotlin 1.6.5+kotlin.1.5.31
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b4463d5
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b446318
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa18
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b446318
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.13+cbda931818
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b446318
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa13
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab6121d5
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b446318
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b446318
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee18
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.4+cbda931818
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+cbda931818
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.3+4658223018
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b446313
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.14+4658223018
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.4+4658223018
		fabric-rendering-v1: Fabric Rendering (v1) 1.8.2+ffb6d41e18
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.8+a00e834b18
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+198a96213d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+cbda931818
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.13+5ab9934c18
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.1+b06cb95b18
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b446318
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab6121d5
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.3.1+4658223018
		fabricloader: Fabric Loader 0.11.6
		facility: Facility 0.12.224
		fake-player-api: Fake Player API 0.2.0
		fallflyinglib: FallFlyingLib 3.0.0-beta.2
		fallingleaves: Falling Leaves 1.7.3+1.17.1
		fallingtree: FallingTree 2.12.1
		fasttransferlib: Fast Transfer Lib 0.5.5
		fermion: Fermion 2.11.244
		fermion-gui: Fermion GUI 2.6.244
		fermion-modkeys: Fermion Modifier Keys 1.10.244
		fermion-orientation: Fermion Orientation 1.2.244
		fermion-varia: Fermion Varia 2.6.244
		ferritecore: FerriteCore 3.0.3
		fiber: fiber 0.23.0-2
		fiber2cloth: Fiber To Cloth 3.1.1
		flan: Flan 1.17.1-1.6.2
		fluidity: Fluidity 0.16.218
		flytre-lib-base: Flytre Lib - Base Module 1.2.0
		flytre-lib-compat: Flytre Lib - Compat Module 1.0.0
		flytre-lib-config: Flytre Lib - Config Module 1.1.0
		flytre-lib-event: Flytre Lib - Event Module 1.0.1
		flytre-lib-gui: Flytre Lib - GUI Module 1.0.0
		flytre-lib-storage: Flytre Lib - Storage Module 2.3.1
		flytre_lib: Flytre Lib 1.3.9
		fonthack: Font Hack 2.4.65
		gearreborn: Gear Reborn 1.17-0.1.10
		geckolib3: Geckolib 3.0.15
		genesis: Genesis 0.7
		glassential: Glassential 1.17-1.2.0
		gobber2: Gobber2 2.4.51
		guardiansgalore: GuardiansGalore 1.17.1-2.1
		haulinghog: Hauling Hog 1.0.3
		horizontalpanes: Horizontal Panes 1.1.5
		hwg: Happiness is a Warm Gun 1.0.20
		illuminations: Illuminations 1.7.2
		impersonate: Impersonate 2.3.5
		improved-stations: Improved Stations 2.0.7
		indium: Indium 1.0.0+mc1.17.1
		indrev: Industrial Revolution 1.10.0-alpha.12
		indrev-nikolite: Industrial Revolution: Nikolite Expansion 1.0+1.17.1
		inmis: Inmis 2.3.2-1.17.1
		iris: Iris 1.1.2+build.9
		jankson: Jankson 3.0.1+j1.2.0
		java: OpenJDK 64-Bit Server VM 16
		kanos_config: Kanos Config 0.1.4+1.14.4-1.17.1
		kirin: Kirin UI 1.9.1
		krypton: Krypton 0.1.4
		ktdatataglib: KtDataTagLib 1.5.4
		lakeside: Lakeside 1.1.0+1.17
		lapiswarps: Lapis Warps 1.0.0+1.17
		lazydfu: LazyDFU 0.1.2
		libblockattributes_core: LibBlockAttributes (Core) 0.9.0
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.9.0
		libblockattributes_items: LibBlockAttributes (Items) 0.9.0
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 4.1.7+1.17.1
		libninepatch: LibNinePatch 1.1.0
		lifts: Lifts 1.3-BETA+1.17
		lightoverlay: Light Overlay 6.0.0
		linkedstorage: Linked Storage 1.3.13-1.17
		lithium: Lithium 0.7.4
		locki: Locki 0.5.0
		lootcrates: Modular Loot Crates 2.0.0
		lovely_snails: Lovely Snails 1.0.3+1.17
		maelstrom_library: Maelstrom Library 1.2.1-1.17
		magna: Magna 0.3.0-1.17-pre4
		matrix: Matrix 1.0.0
		mcda: MC Dungeons Armors 1.7.11
		mcdar: MC Dungeons Artifacts 1.4.1
		mcsa: MC Story Mode Armor 2.3.2-1.17
		midnightlib: MidnightLib 0.2.5
		minecraft: Minecraft 1.17.1
		mining_dims: Mining Dimensions 1.1.12
		mob_catcher: Mob Catcher 1.0.10
		moborigins: Mob Origins 1.6.0
		mocolors: Mo' Colors 1.2.2
		modmenu: Mod Menu 2.0.14
		morevillagers-fabric: MoreVillagersFabric 2.1.1-SNAPSHOT
		mostructures: Mo' Structures 1.3.0-pre1-1.17.1
		mothorigin: A Moth Origin 2.0
		mousewheelie: Mouse Wheelie 1.7.3-newconfig+mc1.17.1-pre1
		multipart_entities: MultipartEntities 1.1.2-1.17
		ninjaphenix_container_lib: NinjaPhenix's Container Library 1.2.2
		notenoughcrashes: Not Enough Crashes 3.6.5+1.17.1
		npcvariety: NPC Variety 2.1.3
		nyfsquivers: Nyf's Quivers Fabric-0.2.6
		omega-config: OmegaConfig 1.0.8
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.31
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.31
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.2
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.0
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.0
		org_jgrapht_jgrapht-core: jgrapht-core 1.1.0
		origins: Origins 1.1.0
		origins-classes: Origins: Classes 1.2.2
		owo: OwO 0.1.1
		pandamc_concreteplus: Concrete plus 1.9
		pandemonium: Requiem: Pandemonium 2.0.0-alpha.12
		pandemoniumapi: Requiem: Pandemonium-API 2.0.0-alpha.12
		patchouli: Patchouli 1.17-54-FABRIC
		pehkui: Pehkui 2.4.0+1.14.4-1.17.1
		penguinorigin: A Penguin Origin 2.0
		placeholder-api: Placeholder API 1.1.0+1.17.1
		playerabilitylib: Pal 1.3.0
		polymorph: Polymorph 0.0.14-1.17.1
		presencefootsteps: Presence Footsteps r32-1.17-rc1
		pugh_lib: Pugh Lib ${version}
		pugh_tools: Pugh Tools ${version}
		quarrymod: Industial Quarry Mod 0.4.3
		quarryplus: QuarryPlus 17.0.390
		rangers_haven: Ranger's Haven 2.3.1
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		reborncore: Reborn Core 5.0.8-beta+build.111
		repurposed_structures: Repurposed Structures 2.3.4+1.17.1
		requiem: Requiem 2.0.0-alpha.12
		requiem-core: Requiem-Core 2.0.0-alpha.12
		requiemapi: Requiem-API 2.0.0-alpha.12
		respawnablepets: Respawnable Pets 1.17-3
		rightclickharvest: Right Click Harvest 1.4.0
		ringsofascension: Rings of Ascension 1.0.1
		roughlyenoughitems: Roughly Enough Items 6.0.279-alpha
		rpgdifficulty: Rpg Difficulty 1.0.7
		satin: Satin 1.6.4
		scorch: Scorch 1.1.2
		seedy-behavior: Seedy Behavior 1.0.2+1.17.1
		simple_backpack: SimpleBackpack 1.1.19
		simpletransport: SimpleTransport 1.0.0-1.17.1
		skinlayers: 3d Skin Layers 1.1.0
		slimeology: Slimeology 0.1.2+1.17.1
		slotlink: slotlink 3.1.5
		sodium: Sodium 0.3.2+IRIS2-build.9
		somnus: Somnus API 0.0.14-1.17.1
		special-circumstances: Special Circumstances 1.9.244
		spirit: Spirit 1.1.0
		stacc: Stacc 1.2.3
		starlight: Starlight 1.0.0+fabric.73f6d37
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		stoneholm: Stoneholm 1.3
		stonevaults: Stonevaults 1.1.0
		stuffz: StuffZ 2.3.2
		talking-villagers: Talking Villagers 1.1.3
		team_reborn_energy: Energy 2.0.0-beta1
		techreborn: Tech Reborn 5.0.8-beta+build.111
		terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.4
		terraform-wood-api-v1: Terraform Wood API (v1) 2.0.2
		terralith: Terralith for Fabric 1.6.1
		thermalconversion: Thermal Conversion 4.0.0+1.17.1
		trinkets: Trinkets 3.0.4
		truerooms: True Secret Rooms 1.1.5
		tweed4_annotated: tweed4_annotated 1.0.0
		tweed4_base: tweed4_base 1.0.0
		tweed4_data: tweed4_data 1.0.0
		tweed4_data_hjson: tweed4_data_hjson 1.0.0
		tweed4_tailor_coat: tweed4_tailor_coat 1.0.0
		tweed4_tailor_screen: tweed4_tailor_screen 1.0.0
		universal_ores: Universal Ores 1.0
		voidz: VoidZ 1.0.5
		wands: Building Wands 2.2.5_mc1.17.1
		waystones: Waystones 2.1.2
		wirelessnetworks: Wireless Networks 1.1.2
		worldedit: WorldEdit 7.2.6+4b2d1e7
		wthit: wthit 3.9.3
		xaerominimap: Xaero's Minimap 21.17.2
		xaeroworldmap: Xaero's World Map 1.17.1
		xp_storage: XP Storage 1.4.2+1.17.1
		xps: Xp Obelisk 0.2.0_for_1.17.x_Fabric
		yungsapi: YUNG's API 1.17-Fabric-19
	Launched Version: fabric-loader-0.11.6-1.17.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce GTX 1070/PCIe/SSE2 GL version 3.2.0 NVIDIA 472.12, NVIDIA Corporation
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: 8x Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz
	Suspected Mods: Fabric Loader (fabricloader)
```

**Comment by CreepyCre** [comment]
I don't think we touch anything that is involved in this crash, though I would probably need to have someone else look over it as well.
I see you are using quite a lot of mods. can you check the following:
1. Does the crash still happen without DimDoors?
2. If so, does the crash happen with only DimDoors?
3. If not, which mod(s) is/ are incompatible with DimDoors of the ones you are using rn. For this you can do the old method of taking out half the mods and checking whether the crash still occurs -> rinse and repeat until the exact mod combination is narrowed down. Checking whether it is caused by Iris or Sodium seems like a good place to start.

**Comment by AmonRay** [comment]
no crashes without DimDoors. Also, everything works with prev version of DimensionalDoors-4.0.0+beta.3-26.07.2021

**Comment by Sharterra** [comment]
Mining Dimensions might be one of the issues.  I know it doesn't play nice with other dimension mods like Atlantis on 1.17.
