### ISSUE TITLE
the minecraft is crashes when i open it 

### ISSUE THREAD

**Issue by momoraz** [DimensionalDevelopment/DimDoors#259]
when i downlowd the 1.17 verison and is crashes and if i have a GeckoLib is just do the same think crashes
is says
ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
Replace 'Minecraft' (minecraft) 1.17 with any version between 1.17.1-rc (inclusive) and 1.18- (exclusive).
Unmet dependency listing:
Mod 'Fabric API' (fabric) 0.45.2+1.17 requires any version between 1.17.1-rc (inclusive) and 1.18- (exclusive) of 'Minecraft' (minecraft), but only the wrong version is present: 1.17!
'Minecraft' (minecraft) 1.17 is an environment reference and usually requires installation or launcher changes to adjust
Inactive mods:
'Minecraft' (minecraft) 1.17, reason: to replace
<html>at net.fabricmc.loader.impl.discovery.ModResolver.findCompatibleSet(ModResolver.java:159)<br/>at net.fabricmc.loader.impl.discovery.ModResolver.resolve(ModResolver.java:45)<br/>at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:224)<br/>at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:187)<br/>at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142)<br/>at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)<br/>at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)</html>

and i dont know why

**Comment by demoman2** [comment]
maybe read it

**Comment by momoraz** [comment]
i read it but i dont know what to do

**Comment by momoraz** [comment]
explain to me
