### ISSUE TITLE
Loot bag corruption

### ISSUE THREAD

**Issue by justinpierson** [DimensionalDevelopment/DimDoors#29]
Kept getting this error, which causes the loot bags to be the purple missing icon, I isolated it by removing all other mods except for LootBags-1.12.2-2.5.3b.jar and dimdoors-3.0.0-beta-4.jar and error was still there, removed dimdoors and the error stopped.

```[16:30:24] [main/ERROR]: Exception loading model for variant lootbags:itemlootbag#inventory, normal location exception: 
net.minecraftforge.client.model.ModelLoaderRegistry$LoaderException: Exception loading model lootbags:item/itemlootbag with loader VanillaLoader.INSTANCE, skipping
	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:153) ~[ModelLoaderRegistry.class:?]
	at net.minecraftforge.client.model.ModelLoader.func_177590_d(ModelLoader.java:298) ~[ModelLoader.class:?]
	at net.minecraft.client.renderer.block.model.ModelBakery.func_177577_b(ModelBakery.java:175) ~[cgb.class:?]
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:161) ~[ModelLoader.class:?]
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28) [cgc.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121) [cev.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:512) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_144]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_144]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_144]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_144]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.io.FileNotFoundException: lootbags:models/item/itemlootbag.json
	at net.minecraft.client.resources.FallbackResourceManager.func_110536_a(FallbackResourceManager.java:69) ~[cei.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SimpleReloadableResourceManager.java:65) ~[cev.class:?]
	at net.minecraft.client.renderer.block.model.ModelBakery.func_177594_c(ModelBakery.java:334) ~[cgb.class:?]
	at net.minecraftforge.client.model.ModelLoader.access$1600(ModelLoader.java:127) ~[ModelLoader.class:?]
	at net.minecraftforge.client.model.ModelLoader$VanillaLoader.loadModel(ModelLoader.java:864) ~[ModelLoader$VanillaLoader.class:?]
	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:149) ~[ModelLoaderRegistry.class:?]
	... 14 more
```

**Comment by Robijnvogel** [comment]
@justinpierson could you please share your full `fml-client-latest.log` via pastebin.com?
This stacktrace does not provide us with enough information to properly troubleshoot the issue.

**Comment by ZombieHDGaming** [comment]
![2018-01-11_20 13 33](https://user-images.githubusercontent.com/10361287/34855121-00d4dca2-f70c-11e7-8051-f4032b61d212.png)
Just tested in our dev environment and everything shows fine with no issues

**Comment by justinpierson** [comment]
Here is the pastebin https://pastebin.com/z83SfAkB
Mods:
LootBags-1.12.2-2.5.3b.jar
dimdoors-3.0.0-beta-4.jar
forge-1.12.2-14.23.1.2587-universal.jar

**Comment by Runemoro** [comment]
Could you try checking if this release fixes it? https://github.com/DimensionalDevelopment/DimDoors/releases/tag/untagged-d1de6d85f0283fba9904

**Comment by ZombieHDGaming** [comment]
Hmm, interesting. It does appear Lootbags gets this error in a normal instance, but nothing is wrong.
![2018-01-11_20 23 47](https://user-images.githubusercontent.com/10361287/34855400-75cb5a76-f70d-11e7-9475-5dc280909feb.png)
Tested against the same files, but I am running 2582. I also just tested against 2587 and there was no issue, it was just an error being thrown.

**Comment by justinpierson** [comment]
Same-ish exception in the log: https://pastebin.com/k4RC4RzW

**Comment by justinpierson** [comment]
I got the same-ish exception in the log: https://pastebin.com/k4RC4RzW but the textures are no longer purple (I also cleared all the saves/caches/configs just in case) I was not 100% sure the purple texture issue was from dim doors but that is the only error I can find about textures and loot bags. Hope this helps otherwise this mod is pretty awesome.

**Comment by Robijnvogel** [comment]
@justinpierson have you asked the Lootbags development team about this issue?
And if so, where?

**Comment by Runemoro** [comment]
Fixed.
