### ISSUE TITLE
Cannot go to dimensional portal 

### ISSUE THREAD

**Issue by kusayu** [DimensionalDevelopment/DimDoors#292]
Mod version:
4.0.4 1.18.2

Modpack:
AQM2

Description:
when i become server operator i cannot join dimensional doors

error in logs
```
[14:06:56] [Server thread/ERROR]: Teleporting failed with the following exception: 
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_3218.method_14178()" because the return value of "org.dimdev.dimdoors.pockets.PocketGenerationContext.world()" is null
        at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.3) ~[?:?]
        at org.dimdev.dimdoors.pockets.virtual.reference.PocketGeneratorReference.prepareAndPlacePocket(PocketGeneratorReference.java:140) ~[DimensionalDoors-4.0.4-1.18.2.jar:?]
        at org.dimdev.dimdoors.pockets.PocketGenerator.generatePocketV2(PocketGenerator.java:54) ~[DimensionalDoors-4.0.4-1.18.2.jar:?]
        at org.dimdev.dimdoors.pockets.PocketGenerator.generateFromPocketGroupV2(PocketGenerator.java:50) ~[DimensionalDoors-4.0.4-1.18.2.jar:?]
        at org.dimdev.dimdoors.pockets.PocketGenerator.generateDungeonPocketV2(PocketGenerator.java:58) ~[DimensionalDoors-4.0.4-1.18.2.jar:?]
        at org.dimdev.dimdoors.rift.targets.RandomTarget.receiveOther(RandomTarget.java:159) ~[DimensionalDoors-4.0.4-1.18.2.jar:?]
        at org.dimdev.dimdoors.api.rift.target.Target.as(Target.java:16) ~[DimensionalDoors-4.0.4-1.18.2.jar:?]
        at org.dimdev.dimdoors.block.entity.RiftBlockEntity.teleport(RiftBlockEntity.java:194) ~[DimensionalDoors-4.0.4-1.18.2.jar:?]
        at org.dimdev.dimdoors.block.entity.EntranceRiftBlockEntity.innerTeleport(EntranceRiftBlockEntity.java:81) ~[DimensionalDoors-4.0.4-1.18.2.jar:?]
        at org.dimdev.dimdoors.block.entity.EntranceRiftBlockEntity.teleport(EntranceRiftBlockEntity.java:77) ~[DimensionalDoors-4.0.4-1.18.2.jar:?]
        at org.dimdev.dimdoors.block.DimensionalPortalBlock.onEntityCollision(DimensionalPortalBlock.java:66) ~[DimensionalDoors-4.0.4-1.18.2.jar:?]
        at net.minecraft.block.AbstractBlock$AbstractBlockState.onEntityCollision(AbstractBlock:927) ~[?:?]
        at net.minecraft.entity.Entity.checkBlockCollision(Entity:1028) ~[?:?]
        at net.minecraft.entity.Entity.tryCheckBlockCollision(Entity:768) ~[?:?]
        at net.minecraft.entity.Entity.move(Entity:737) ~[?:?]
        at net.minecraft.server.network.ServerPlayNetworkHandler.onPlayerMove(ServerPlayNetworkHandler:903) ~[?:?]
        at net.minecraft.network.packet.c2s.play.PlayerMoveC2SPacket.apply(PlayerMoveC2SPacket:114) ~[?:?]
        at net.minecraft.network.packet.c2s.play.PlayerMoveC2SPacket$PositionAndOnGround.apply(PlayerMoveC2SPacket:42) ~[?:?]
        at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils:22) ~[?:?]
        at net.minecraft.server.ServerTask.run(ServerTask:18) ~[?:?]
        at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:157) ~[?:?]
        at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:808) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:165) ~[server-intermediary.jar:?]
        at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:131) ~[?:?]
        at net.minecraft.server.MinecraftServer.runOneTask(MinecraftServer:790) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.runTask(MinecraftServer:784) ~[server-intermediary.jar:?]
        at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:140) ~[?:?]
        at net.minecraft.server.MinecraftServer.runTasksTillTickEnd(MinecraftServer:769) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.handler$cca000$modifiedRunLoop(MinecraftServer:5905) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:676) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:273) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
[14:07:08] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 2898ms or 57 ticks behind
```

**Comment by kusayu** [comment]
nevermind, once i restart the server it works

**Comment by xErrorAmelie** [comment]
https://mclo.gs/pbXMKyP same issue here. Happens everytime I try to go trough the portal, idk why.
