### ISSUE TITLE
1.18.2 Somthing went wrong. Please report bug. Cant't go throgh DimDoors. 

### ISSUE THREAD

**Issue by DerLordz** [DimensionalDevelopment/DimDoors#305]
Everytime i try to use the DimDoors on my Server i get the message: Something went wrong. Please report Bug.

This is the Console Error

`[05.08 20:24:13] [Server] [Server thread/ERROR]: Teleporting failed with the following exception: 
[05.08 20:24:13] [Server] java.lang.NullPointerExceptionCannot invoke "net.minecraft.class_3218.method_14178()" because the return value of "org.dimdev.dimdoors.pockets.PocketGenerationContext.world()" is null
[05.08 20:24:13] [Server] 	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.4) ~[?:?]
[05.08 20:24:13] [Server] 	at org.dimdev.dimdoors.pockets.virtual.reference.PocketGeneratorReference.prepareAndPlacePocket(PocketGeneratorReference.java:140) ~[DimensionalDoors-4.0.4-1.18.2.jar:?]
[05.08 20:24:13] [Server] 	at org.dimdev.dimdoors.pockets.PocketGenerator.generatePocketV2(PocketGenerator.java:54) ~[DimensionalDoors-4.0.4-1.18.2.jar:?]
[05.08 20:24:13] [Server] 	at org.dimdev.dimdoors.pockets.PocketGenerator.generateFromPocketGroupV2(PocketGenerator.java:50) ~[DimensionalDoors-4.0.4-1.18.2.jar:?]
[05.08 20:24:13] [Server] 	at org.dimdev.dimdoors.pockets.PocketGenerator.generateDungeonPocketV2(PocketGenerator.java:58) ~[DimensionalDoors-4.0.4-1.18.2.jar:?]
[05.08 20:24:13] [Server] 	at org.dimdev.dimdoors.rift.targets.RandomTarget.receiveOther(RandomTarget.java:159) ~[DimensionalDoors-4.0.4-1.18.2.jar:?]
[05.08 20:24:13] [Server] 	at org.dimdev.dimdoors.api.rift.target.Target.as(Target.java:16) ~[DimensionalDoors-4.0.4-1.18.2.jar:?]
[05.08 20:24:13] [Server] 	at org.dimdev.dimdoors.block.entity.RiftBlockEntity.teleport(RiftBlockEntity.java:194) ~[DimensionalDoors-4.0.4-1.18.2.jar:?]
[05.08 20:24:13] [Server] 	at org.dimdev.dimdoors.block.entity.EntranceRiftBlockEntity.innerTeleport(EntranceRiftBlockEntity.java:81) ~[DimensionalDoors-4.0.4-1.18.2.jar:?]
[05.08 20:24:13] [Server] 	at org.dimdev.dimdoors.block.entity.EntranceRiftBlockEntity.teleport(EntranceRiftBlockEntity.java:77) ~[DimensionalDoors-4.0.4-1.18.2.jar:?]
[05.08 20:24:13] [Server] 	at org.dimdev.dimdoors.block.DimensionalPortalBlock.onEntityCollision(DimensionalPortalBlock.java:66) ~[DimensionalDoors-4.0.4-1.18.2.jar:?]
[05.08 20:24:13] [Server] 	at net.minecraft.block.AbstractBlock$AbstractBlockState.onEntityCollision(AbstractBlock:927) ~[?:?]
[05.08 20:24:13] [Server] 	at net.minecraft.entity.Entity.checkBlockCollision(Entity:1028) ~[?:?]
[05.08 20:24:13] [Server] 	at net.minecraft.entity.Entity.tryCheckBlockCollision(Entity:768) ~[?:?]
[05.08 20:24:13] [Server] 	at net.minecraft.entity.Entity.move(Entity:737) ~[?:?]
[05.08 20:24:13] [Server] 	at net.minecraft.server.network.ServerPlayNetworkHandler.onPlayerMove(ServerPlayNetworkHandler:903) ~[?:?]
[05.08 20:24:13] [Server] 	at net.minecraft.network.packet.c2s.play.PlayerMoveC2SPacket.apply(PlayerMoveC2SPacket:114) ~[?:?]
[05.08 20:24:13] [Server] 	at net.minecraft.network.packet.c2s.play.PlayerMoveC2SPacket$Full.apply(PlayerMoveC2SPacket:16) ~[?:?]
[05.08 20:24:13] [Server] 	at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils:22) ~[?:?]
[05.08 20:24:13] [Server] 	at net.minecraft.server.ServerTask.run(ServerTask:18) ~[?:?]
[05.08 20:24:13] [Server] 	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:157) ~[?:?]
[05.08 20:24:13] [Server] 	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23) ~[?:?]
[05.08 20:24:13] [Server] 	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:808) ~[server-intermediary.jar:?]
[05.08 20:24:13] [Server] 	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:165) ~[server-intermediary.jar:?]
[05.08 20:24:13] [Server] 	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:131) ~[?:?]
[05.08 20:24:13] [Server] 	at net.minecraft.server.MinecraftServer.runOneTask(MinecraftServer:790) ~[server-intermediary.jar:?]
[05.08 20:24:13] [Server] 	at net.minecraft.server.MinecraftServer.runTask(MinecraftServer:784) ~[server-intermediary.jar:?]
[05.08 20:24:13] [Server] 	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:116) ~[?:?]
[05.08 20:24:13] [Server] 	at net.minecraft.server.MinecraftServer.runTasksTillTickEnd(MinecraftServer:768) ~[server-intermediary.jar:?]
[05.08 20:24:13] [Server] 	at net.minecraft.server.MinecraftServer.handler$cej000$modifiedRunLoop(MinecraftServer:5905) ~[server-intermediary.jar:?]
[05.08 20:24:13] [Server] 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:676) ~[server-intermediary.jar:?]
[05.08 20:24:13] [Server] 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:273) ~[server-intermediary.jar:?]
[05.08 20:24:13] [Server] 	at java.lang.Thread.run(Thread.java:833) [?:?]`

Any ideas?

**Comment by neo0nymous** [comment]
Hey, seems like we have kinda the same issue. Did you manage to fix it somehow? Best Regards

**Comment by DerLordz** [comment]
I didn't. No idea what to do about it.

**Comment by BoogieMonster1O1** [comment]
Fixed in 1.19.2+
