### ISSUE TITLE
AccessWidenerFormatException [1.19.2]

### ISSUE THREAD

**Issue by Kroko1337** [DimensionalDevelopment/DimDoors#318]
Uncaught exception in thread "main"
java.lang.RuntimeException: Failed to read accessWidener file from mod dimdoors
	at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:441)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:151)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: net.fabricmc.accesswidener.AccessWidenerFormatException: line 1: Namespace (named) does not match current runtime namespace (intermediary)
	at net.fabricmc.accesswidener.AccessWidenerReader.error(AccessWidenerReader.java:285)
	at net.fabricmc.accesswidener.AccessWidenerReader.read(AccessWidenerReader.java:84)
	at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:439)
	... 3 more

**Comment by SylisMC** [comment]
Same
fabric-api-0.62.0+1.19.2.jar
DimensionalDoors-5.0.0-1.19.2-sources.jar
```
Uncaught exception in thread "main"
java.lang.RuntimeException: Failed to read accessWidener file from mod dimdoors
	at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:441)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:151)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: net.fabricmc.accesswidener.AccessWidenerFormatException: line 1: Namespace (named) does not match current runtime namespace (intermediary)
	at net.fabricmc.accesswidener.AccessWidenerReader.error(AccessWidenerReader.java:285)
	at net.fabricmc.accesswidener.AccessWidenerReader.read(AccessWidenerReader.java:84)
	at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:439)
	... 3 more

```

**Comment by SylisMC** [comment]
[latest.log](https://github.com/DimensionalDevelopment/DimDoors/files/9790582/latest.log)

**Comment by Tanden22** [comment]
Same error here:
[latest.log](https://github.com/DimensionalDevelopment/DimDoors/files/9812876/latest.log)

Uncaught exception in thread "main"
java.lang.RuntimeException: Failed to read accessWidener file from mod dimdoors
	at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:441)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:151)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: net.fabricmc.accesswidener.AccessWidenerFormatException: line 1: Namespace (named) does not match current runtime namespace (intermediary)
	at net.fabricmc.accesswidener.AccessWidenerReader.error(AccessWidenerReader.java:285)
	at net.fabricmc.accesswidener.AccessWidenerReader.read(AccessWidenerReader.java:84)
	at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:439)
	... 3 more

**Comment by MistakingManx** [comment]
I also have this issue.
```
Uncaught exception in thread "main"
java.lang.RuntimeException: Failed to read accessWidener file from mod dimdoors
	at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:441)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:151)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: net.fabricmc.accesswidener.AccessWidenerFormatException: line 1: Namespace (named) does not match current runtime namespace (intermediary)
	at net.fabricmc.accesswidener.AccessWidenerReader.error(AccessWidenerReader.java:285)
	at net.fabricmc.accesswidener.AccessWidenerReader.read(AccessWidenerReader.java:84)
	at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:439)
	... 3 more
```

**Comment by Lucidueye** [comment]
I'm having the same issue

> Uncaught exception in thread "main"
java.lang.RuntimeException: Failed to read accessWidener file from mod dimdoors
	at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:441)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:151)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: net.fabricmc.accesswidener.AccessWidenerFormatException: line 1: Namespace (named) does not match current runtime namespace (intermediary)
	at net.fabricmc.accesswidener.AccessWidenerReader.error(AccessWidenerReader.java:285)
	at net.fabricmc.accesswidener.AccessWidenerReader.read(AccessWidenerReader.java:84)
	at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:439)
	... 3 more

The game crashes soon after

**Comment by feastfortheworms** [comment]
The additional file is the correct one to download for 1.19.2. If you got it from curseforge, they seem to have been accidentally uploaded in the wrong places. (quote "Note: The sources for 5.0.0 was uploaded before the actual mod by accident due being uploaded in the middle of the night by someone very tired. The additional file is the actual mod.") Should be the other way around. I had the same error when I used the main file (which is the sources file), no issues when using the additional instead. Make sure the filename doesn't end with sources.jar and you should be good.
