### ISSUE TITLE
[Bug]: Some types of gateways always fail to teleport

### ISSUE THREAD

**Issue by Gaming32** [DimensionalDevelopment/DimDoors#326]
### What happened?

When I attempt to go through a gateway, it always "fails to teleport" me. I did generate the gateways with `/place feature`.

Quilt: 0.17.8
Modpack: [Wild Liminal](https://modrinth.com/modpack/wild-liminal)

### Mod Version

5.0.1

### What versions of Minecraft does this issue happen on?

1.19.2

### Log

```shell
[17:46:09] [Server thread/INFO]: Generating pocket from template dimdoors:dungeon/break_block_boom at location class_2338{x=-256, y=0, z=240}
[17:46:09] [Server thread/ERROR]: Teleporting failed with the following exception: 
java.lang.NullPointerException: Cannot invoke "org.dimdev.dimdoors.block.entity.RiftBlockEntity.updateColor()" because the return value of "org.dimdev.dimdoors.api.util.Location.getBlockEntity()" is null
	at org.dimdev.dimdoors.rift.registry.Rift.markDirty(Rift.java:63) ~[DimensionalDoors-5.0.1-1.19.2.jar:?]
	at org.dimdev.dimdoors.rift.registry.RiftRegistry.addRift(RiftRegistry.java:205) ~[DimensionalDoors-5.0.1-1.19.2.jar:?]
	at org.dimdev.dimdoors.block.entity.RiftBlockEntity.register(RiftBlockEntity.java:139) ~[DimensionalDoors-5.0.1-1.19.2.jar:?]
	at org.dimdev.dimdoors.pockets.TemplateUtils.registerRifts(TemplateUtils.java:101) ~[DimensionalDoors-5.0.1-1.19.2.jar:?]
	at org.dimdev.dimdoors.pockets.generator.PocketGenerator.setup(PocketGenerator.java:263) ~[DimensionalDoors-5.0.1-1.19.2.jar:?]
	at org.dimdev.dimdoors.pockets.virtual.reference.PocketGeneratorReference.prepareAndPlacePocket(PocketGeneratorReference.java:191) ~[DimensionalDoors-5.0.1-1.19.2.jar:?]
	at org.dimdev.dimdoors.pockets.PocketGenerator.generatePocketV2(PocketGenerator.java:54) ~[DimensionalDoors-5.0.1-1.19.2.jar:?]
	at org.dimdev.dimdoors.pockets.PocketGenerator.generateFromPocketGroupV2(PocketGenerator.java:50) ~[DimensionalDoors-5.0.1-1.19.2.jar:?]
	at org.dimdev.dimdoors.pockets.PocketGenerator.generateDungeonPocketV2(PocketGenerator.java:58) ~[DimensionalDoors-5.0.1-1.19.2.jar:?]
	at org.dimdev.dimdoors.rift.targets.RandomTarget.receiveOther(RandomTarget.java:159) ~[DimensionalDoors-5.0.1-1.19.2.jar:?]
	at org.dimdev.dimdoors.api.rift.target.Target.as(Target.java:16) ~[DimensionalDoors-5.0.1-1.19.2.jar:?]
	at org.dimdev.dimdoors.block.entity.RiftBlockEntity.teleport(RiftBlockEntity.java:195) ~[DimensionalDoors-5.0.1-1.19.2.jar:?]
	at org.dimdev.dimdoors.block.entity.EntranceRiftBlockEntity.innerTeleport(EntranceRiftBlockEntity.java:82) ~[DimensionalDoors-5.0.1-1.19.2.jar:?]
	at org.dimdev.dimdoors.block.entity.EntranceRiftBlockEntity.teleport(EntranceRiftBlockEntity.java:78) ~[DimensionalDoors-5.0.1-1.19.2.jar:?]
	at org.dimdev.dimdoors.block.DimensionalPortalBlock.method_9548(DimensionalPortalBlock.java:66) ~[DimensionalDoors-5.0.1-1.19.2.jar:?]
	at net.minecraft.class_4970$class_4971.method_26178(class_4970.java:952) ~[client-intermediary.jar:?]
	at net.minecraft.class_1297.method_5852(class_1297.java:1059) ~[client-intermediary.jar:?]
	at net.minecraft.class_1297.method_36974(class_1297.java:783) ~[client-intermediary.jar:?]
	at net.minecraft.class_1297.method_5784(class_1297.java:752) ~[client-intermediary.jar:?]
	at net.minecraft.class_3244.method_12063(class_3244.java:965) ~[client-intermediary.jar:?]
	at net.minecraft.class_2828.method_12272(class_2828.java:114) ~[client-intermediary.jar:?]
	at net.minecraft.class_2828$class_2829.method_11054(class_2828.java:42) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[client-intermediary.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:776) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:159) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:758) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:116) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:736) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:669) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```
```

**Comment by Gaming32** [comment]
End gateways work fine. Also, the failure generates a rift. The rift can be opened with a Rift Blade, then it works.
