### ISSUE TITLE
[Bug]: Doors not working after changing world over to new server provider

### ISSUE THREAD

**Issue by AbysslessVoid** [DimensionalDevelopment/DimDoors#338]
### What happened?

After transferring server providers all the portals in our world that have not already been gone through before the switch have stopped working and saying there is a bug and to report it.

Minecraft version is: 1.9.2 but its not letting me change it to that.

Hopefully I did this right sorry!

### Mod Version

_[1.19.2] Dimensional Doors 5.0.2-1.19.2]_

### What versions of Minecraft does this issue happen on?

1.19.3

### Log

```shell
07.02 06:18:33 [Server] Server thread/ERROR Teleporting failed with the following exception: 
07.02 06:18:33 [Server] INFO java.lang.NullPointerException: Cannot invoke "org.dimdev.dimdoors.pockets.virtual.VirtualPocket.getNextPocketGeneratorReference(org.dimdev.dimdoors.pockets.PocketGenerationContext)" because the return value of "org.dimdev.dimdoors.pockets.PocketLoader.getGroup(net.minecraft.class_2960)" is null
07.02 06:18:33 [Server] INFO at org.dimdev.dimdoors.pockets.PocketGenerator.generateFromPocketGroupV2(PocketGenerator.java:50) ~[DimensionalDoors-5.0.2-1.19.2%20(1).jar:?]
07.02 06:18:33 [Server] INFO at org.dimdev.dimdoors.pockets.PocketGenerator.generateDungeonPocketV2(PocketGenerator.java:58) ~[DimensionalDoors-5.0.2-1.19.2%20(1).jar:?]
07.02 06:18:33 [Server] INFO at org.dimdev.dimdoors.rift.targets.RandomTarget.receiveOther(RandomTarget.java:159) ~[DimensionalDoors-5.0.2-1.19.2%20(1).jar:?]
07.02 06:18:33 [Server] INFO at org.dimdev.dimdoors.api.rift.target.Target.as(Target.java:16) ~[DimensionalDoors-5.0.2-1.19.2%20(1).jar:?]
07.02 06:18:33 [Server] INFO at org.dimdev.dimdoors.block.entity.RiftBlockEntity.teleport(RiftBlockEntity.java:195) ~[DimensionalDoors-5.0.2-1.19.2%20(1).jar:?]
07.02 06:18:33 [Server] INFO at org.dimdev.dimdoors.block.entity.EntranceRiftBlockEntity.innerTeleport(EntranceRiftBlockEntity.java:82) ~[DimensionalDoors-5.0.2-1.19.2%20(1).jar:?]
07.02 06:18:33 [Server] INFO at org.dimdev.dimdoors.block.entity.EntranceRiftBlockEntity.teleport(EntranceRiftBlockEntity.java:78) ~[DimensionalDoors-5.0.2-1.19.2%20(1).jar:?]
07.02 06:18:33 [Server] INFO at org.dimdev.dimdoors.block.door.DimensionalDoorBlock.onCollision(DimensionalDoorBlock.java:121) ~[DimensionalDoors-5.0.2-1.19.2%20(1).jar:?]
07.02 06:18:33 [Server] INFO at org.dimdev.dimdoors.block.door.DimensionalDoorBlock.onAfterMovePlayerCollision(DimensionalDoorBlock.java:65) ~[DimensionalDoors-5.0.2-1.19.2%20(1).jar:?]
07.02 06:18:33 [Server] INFO at net.minecraft.class_3244.handler$zfj000$checkBlockCollision(class_3244.java:3544) ~[server-intermediary.jar:?]
07.02 06:18:33 [Server] INFO at net.minecraft.class_3244.method_12063(class_3244.java:1017) ~[server-intermediary.jar:?]
07.02 06:18:33 [Server] INFO at net.minecraft.class_2828.method_12272(class_2828.java:114) ~[server-intermediary.jar:?]
07.02 06:18:33 [Server] INFO at net.minecraft.class_2828$class_2830.method_11054(class_2828.java:16) ~[server-intermediary.jar:?]
07.02 06:18:33 [Server] INFO at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[server-intermediary.jar:?]
07.02 06:18:33 [Server] INFO at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
07.02 06:18:33 [Server] INFO at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[server-intermediary.jar:?]
07.02 06:18:33 [Server] INFO at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
07.02 06:18:33 [Server] INFO at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:776) ~[server-intermediary.jar:?]
07.02 06:18:33 [Server] INFO at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:159) ~[server-intermediary.jar:?]
07.02 06:18:33 [Server] INFO at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[server-intermediary.jar:?]
07.02 06:18:33 [Server] INFO at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:758) ~[server-intermediary.jar:?]
07.02 06:18:33 [Server] INFO at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752) ~[server-intermediary.jar:?]
07.02 06:18:33 [Server] INFO at net.minecraft.class_1255.method_18857(class_1255.java:140) ~[server-intermediary.jar:?]
07.02 06:18:33 [Server] INFO at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:737) ~[server-intermediary.jar:?]
07.02 06:18:33 [Server] INFO at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:669) ~[server-intermediary.jar:?]
07.02 06:18:33 [Server] INFO at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[server-intermediary.jar:?]
07.02 06:18:33 [Server] INFO at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by BoogieMonster1O1** [comment]
Does this happen on 1.19.3?
