### ISSUE TITLE
[Bug]: Crash when using Rift Configurator

### ISSUE THREAD

**Issue by toasty02** [DimensionalDevelopment/DimDoors#339]
### What happened?

Forcably exits game when shift click rift configurator on quartz door.

[crash-2023-02-12_14.22.22-client.txt](https://github.com/DimensionalDevelopment/DimDoors/files/10715229/crash-2023-02-12_14.22.22-client.txt)

### Mod Version

3.0.12

### What versions of Minecraft does this issue happen on?

1.12.2

### Log

```shell
---- Minecraft Crash Report ----
// You're mean.

Time: 2/12/23 2:22 PM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at org.dimdev.dimdoors.client.GUIConfigScreen.func_73863_a(GUIConfigScreen.java:142)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at org.dimdev.dimdoors.client.GUIConfigScreen.func_73863_a(GUIConfigScreen.java:142)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)

-- Screen render details --
Details:
	Screen name: org.dimdev.dimdoors.client.GUIRiftConfigScreen
	Mouse location: Scaled: (171, 127). Absolute: (512, 384)
	Screen size: Scaled: (342, 256). Absolute: (1024, 768). Scale factor of 3

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['DDGiuseppi'/23, l='MpServer', x=-797.50, y=4.00, z=392.50]]
	Chunk stats: MultiplayerChunkCache: 554, 554
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-803,4,392), Chunk: (at 13,0,8 in -51,24; contains blocks -816,0,384 to -801,255,399), Region: (-2,0; contains chunks -64,0 to -33,31, blocks -1024,0,0 to -513,255,511)
	Level time: 420 game time, 420 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 31 total; [EntitySlime['Slime'/35137, l='MpServer', x=-842.75, y=4.14, z=358.10], EntitySheep['Sheep'/77381, l='MpServer', x=-727.50, y=4.00, z=466.50], EntitySlime['Slime'/52933, l='MpServer', x=-839.76, y=4.00, z=342.75], EntitySheep['Sheep'/77380, l='MpServer', x=-722.50, y=4.00, z=468.50], EntitySlime['Slime'/16646, l='MpServer', x=-812.16, y=4.00, z=429.76], EntitySheep['Sheep'/77383, l='MpServer', x=-728.50, y=4.00, z=466.50], EntitySheep['Sheep'/77382, l='MpServer', x=-726.50, y=4.00, z=466.50], EntitySlime['Slime'/57741, l='MpServer', x=-775.01, y=4.92, z=420.60], EntitySheep['Sheep'/77331, l='MpServer', x=-867.50, y=4.00, z=322.50], EntitySheep['Sheep'/77395, l='MpServer', x=-722.50, y=4.00, z=441.50], EntitySheep['Sheep'/77394, l='MpServer', x=-721.50, y=4.00, z=441.50], EntitySlime['Slime'/21844, l='MpServer', x=-760.66, y=4.00, z=373.33], EntitySheep['Sheep'/77333, l='MpServer', x=-866.50, y=4.00, z=320.50], EntitySlime['Slime'/43541, l='MpServer', x=-847.63, y=4.00, z=426.43], EntitySheep['Sheep'/77332, l='MpServer', x=-866.50, y=4.00, z=324.50], EntitySheep['Sheep'/77334, l='MpServer', x=-870.50, y=4.00, z=322.50], EntitySheep['Sheep'/77337, l='MpServer', x=-759.50, y=4.00, z=312.50], EntitySlime['Slime'/8736, l='MpServer', x=-783.18, y=4.00, z=452.50], EntitySheep['Sheep'/77347, l='MpServer', x=-845.50, y=4.00, z=402.50], EntitySheep['Sheep'/77349, l='MpServer', x=-848.50, y=4.00, z=409.50], EntitySheep['Sheep'/77348, l='MpServer', x=-848.50, y=4.00, z=406.50], EntitySheep['Sheep'/77350, l='MpServer', x=-848.50, y=4.00, z=404.50], EntitySlime['Slime'/39530, l='MpServer', x=-841.48, y=4.00, z=336.60], EntitySlime['Slime'/69226, l='MpServer', x=-820.54, y=4.00, z=354.42], EntityChicken['Chicken'/77363, l='MpServer', x=-731.50, y=4.00, z=368.50], EntityChicken['Chicken'/77364, l='MpServer', x=-729.50, y=4.00, z=371.50], EntityChicken['Chicken'/77367, l='MpServer', x=-733.50, y=4.00, z=376.50], EntityChicken['Chicken'/77369, l='MpServer', x=-726.50, y=4.00, z=366.50], EntitySlime['Slime'/21305, l='MpServer', x=-796.56, y=4.00, z=455.27], EntitySlime['Slime'/23037, l='MpServer', x=-841.30, y=4.00, z=383.32], EntityPlayerSP['DDGiuseppi'/23, l='MpServer', x=-797.50, y=4.00, z=392.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1141324352 bytes (1088 MB) / 1589116928 bytes (1515 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID        | Version      | Source                             | Signature                                |
	|:------ |:--------- |:------------ |:---------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft | 1.12.2       | minecraft.jar                      | None                                     |
	| LCHIJA | mcp       | 9.42         | minecraft.jar                      | None                                     |
	| LCHIJA | FML       | 8.0.99.99    | forge-1.12.2-14.23.5.2860.jar      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge     | 14.23.5.2860 | forge-1.12.2-14.23.5.2860.jar      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | dimdoors  | 3.0.10       | DimensionalDoors-1.12.2-3.0.12.jar | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 528.49' Renderer: 'NVIDIA GeForce RTX 3080/PCIe/SSE2'
	Launched Version: forge-14.23.5.2860
	LWJGL: 2.9.4
	OpenGL: NVIDIA GeForce RTX 3080/PCIe/SSE2 GL version 4.6.0 NVIDIA 528.49, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 16x AMD Ryzen 7 5800X 8-Core Processor
```

**Comment by TheComputerizer** [comment]
The rift configurator is not yet implemented for 1.12.2
