### ISSUE TITLE
[Bug]: Incompatibility with create. Schematics | "net.minecraft.World.getRegistryKey()" is null 

### ISSUE THREAD

**Issue by Zardexd** [DimensionalDevelopment/DimDoors#373]
### What happened?
**Cant use create schematic with Dimdoors installed. Tested only placing in gm1 manually. Cannon wasn't tested**

_**Reproducing - Install both mods, create a schematic in create, try to paste it.**_

### Mod Version

5.3.0

### What versions of Minecraft does this issue happen on?

**Fabric 0.14.24 , Minecraft 1.20.1 , Create-fabric-0.5.1-d-build**

### Full logs 
https://mclo.gs/QRGXd7F
[latest.log](https://github.com/DimensionalDevelopment/DimDoors/files/13444937/latest.log) 

### Log

```shell
[01:49:19] [Server thread/INFO]: Zardexd joined the game
[01:49:20] [Render thread/WARN]: Unknown recipe category: dimdoors:shaped_tesselating/dimdoors:tesselating/enduring_fibers
[01:49:20] [Render thread/WARN]: Unknown recipe category: dimdoors:shaped_tesselating/dimdoors:tesselating/world_thread_leggings
[01:49:20] [Render thread/WARN]: Unknown recipe category: dimdoors:shaped_tesselating/dimdoors:tesselating/fabric_of_reality
[01:49:20] [Render thread/WARN]: Unknown recipe category: dimdoors:shaped_tesselating/dimdoors:tesselating/world_thread_helmet
[01:49:20] [Render thread/WARN]: Unknown recipe category: dimdoors:shaped_tesselating/dimdoors:tesselating/world_thread_chestplate
[01:49:20] [Render thread/WARN]: Unknown recipe category: dimdoors:shaped_tesselating/dimdoors:tesselating/fabric_of_finality
[01:49:20] [Render thread/WARN]: Unknown recipe category: dimdoors:shaped_tesselating/dimdoors:tesselating/fuzzy_fireball
[01:49:20] [Render thread/WARN]: Unknown recipe category: dimdoors:shaped_tesselating/dimdoors:tesselating/world_thread_boots
[01:49:20] [Render thread/WARN]: Unknown recipe category: dimdoors:shaped_tesselating/dimdoors:tesselating/stable_fabric
[01:49:20] [Render thread/WARN]: Unknown recipe category: dimdoors:shaped_tesselating/dimdoors:tesselating/rift_pearl
[01:49:20] [Render thread/WARN]: Unknown recipe category: dimdoors:shapeless_tesselating/dimdoors:tesselating/rift_blade
[01:49:20] [Render thread/WARN]: Unknown recipe category: dimdoors:shaped_tesselating/dimdoors:tesselating/liminal_lint
[01:49:20] [Render thread/WARN]: Unknown recipe category: dimdoors:shaped_tesselating/dimdoors:tesselating/reality_sponge
[01:49:20] [Render thread/INFO]: Loaded 18 advancements
[01:49:25] [Server thread/INFO]: Saving and pausing game...
[01:49:25] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
[01:49:25] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/dimdoors:limbo
[01:49:25] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/dimdoors:public_pockets
[01:49:25] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/dimdoors:personal_pockets
[01:49:25] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/dimdoors:dungeon_pockets
[01:49:25] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end
[01:49:25] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether
[01:49:25] [Render thread/INFO]: [System] [CHAT] You are at x = 4, y = ?, z = -164, w = 5
[01:49:48] [Server thread/INFO]: Saving and pausing game...
[01:49:48] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
[01:49:48] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/dimdoors:limbo
[01:49:48] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/dimdoors:public_pockets
[01:49:48] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/dimdoors:personal_pockets
[01:49:48] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/dimdoors:dungeon_pockets
[01:49:48] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end
[01:49:48] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether
[01:50:03] [Server thread/INFO]: New Schematic Uploaded: Zardexd/123123.nbt
[01:50:06] [Render thread/INFO]: [System] [CHAT] Schematic failed to Load - Check Game Logs
[01:50:06] [Render thread/ERROR]: Failed to load Schematic for Previewing
java.lang.NullPointerException: Cannot invoke "Object.equals(Object)" because the return value of "net.minecraft.class_1937.method_27983()" is null
	at org.dimdev.dimdoors.world.level.registry.fabric.DimensionalRegistryImpl.createImpl(DimensionalRegistryImpl.java:29) ~[dimdoors-5.3.0-fabric-beta2.jar:?]
	at dev.onyxstudios.cca._generated_.GeneratedComponentContainer_0.<init>(Unknown Source) ~[?:?]
	at dev.onyxstudios.cca._generated_.GeneratedContainerFactory_0.createContainer(Unknown Source) ~[?:?]
	at net.minecraft.class_1937.handler$zkb000$cardinal-components-world$initComponents(class_1937.java:1565) ~[client-intermediary.jar:?]
	at net.minecraft.class_1937.<init>(class_1937.java:163) ~[client-intermediary.jar:?]
	at com.simibubi.create.content.schematics.SchematicChunkSource$EmptierChunk$DummyLevel.<init>(SchematicChunkSource.java:104) ~[create-fabric-0.5.1-d-build.1161+mc1.20.1.jar:?]
	at com.simibubi.create.content.schematics.SchematicChunkSource$EmptierChunk$DummyLevel.<init>(SchematicChunkSource.java:112) ~[create-fabric-0.5.1-d-build.1161+mc1.20.1.jar:?]
	at com.simibubi.create.content.schematics.SchematicChunkSource$EmptierChunk.<init>(SchematicChunkSource.java:231) ~[create-fabric-0.5.1-d-build.1161+mc1.20.1.jar:?]
	at com.simibubi.create.content.schematics.SchematicChunkSource.getChunk(SchematicChunkSource.java:75) ~[create-fabric-0.5.1-d-build.1161+mc1.20.1.jar:?]
	at com.simibubi.create.content.schematics.SchematicChunkSource.method_12121(SchematicChunkSource.java:71) ~[create-fabric-0.5.1-d-build.1161+mc1.20.1.jar:?]
	at net.minecraft.class_2802.method_12123(class_2802.java:28) ~[client-intermediary.jar:?]
	at net.minecraft.class_1936.method_8393(class_1936.java:79) ~[client-intermediary.jar:?]
	at net.minecraft.class_4538.method_33598(class_4538.java:208) ~[client-intermediary.jar:?]
	at net.minecraft.class_4538.method_22340(class_4538.java:216) ~[client-intermediary.jar:?]
	at net.minecraft.class_1937.method_8524(class_1937.java:715) ~[client-intermediary.jar:?]
	at net.minecraft.class_2586.method_31663(class_2586.java:152) ~[client-intermediary.jar:?]
	at net.minecraft.class_2586.method_5431(class_2586.java:147) ~[client-intermediary.jar:?]
	at net.minecraft.class_3499.method_15172(class_3499.java:340) ~[client-intermediary.jar:?]
	at com.simibubi.create.content.schematics.client.SchematicHandler.setupRenderer(SchematicHandler.java:165) ~[create-fabric-0.5.1-d-build.1161+mc1.20.1.jar:?]
	at com.simibubi.create.content.schematics.client.SchematicHandler.deploy(SchematicHandler.java:364) ~[create-fabric-0.5.1-d-build.1161+mc1.20.1.jar:?]
	at com.simibubi.create.content.schematics.client.tools.DeployTool.handleRightClick(DeployTool.java:106) ~[create-fabric-0.5.1-d-build.1161+mc1.20.1.jar:?]
	at com.simibubi.create.content.schematics.client.SchematicHandler.onMouseInput(SchematicHandler.java:269) ~[create-fabric-0.5.1-d-build.1161+mc1.20.1.jar:?]
	at com.simibubi.create.foundation.events.InputEvents.onMouseInput(InputEvents.java:49) ~[create-fabric-0.5.1-d-build.1161+mc1.20.1.jar:?]
	at io.github.fabricators_of_create.porting_lib.event.client.MouseInputEvents.lambda$static$0(MouseInputEvents.java:17) ~[porting_lib_base-2.1.1127+1.20-ea6282156cba7170.jar:?]
	at net.minecraft.class_312.handler$zfd000$porting_lib_base$port_lib$beforeMouseButton(class_312.java:538) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1601(class_312.java:85) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22686(class_312.java:169) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:102) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22684(class_312.java:169) ~[client-intermediary.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.1.jar:?]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar:?]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474) ~[lwjgl-glfw-3.3.1.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:237) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1244) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.24.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[NewLaunch.jar:?]
[01:52:23] [Server thread/INFO]: Saving and pausing game...
[01:52:23] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
[01:52:23] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/dimdoors:limbo
[01:52:23] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/dimdoors:public_pockets
[01:52:23] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/dimdoors:personal_pockets
[01:52:23] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/dimdoors:dungeon_pockets
[01:52:23] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end
[01:52:23] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether
[01:52:24] [Server thread/INFO]: Zardexd lost connection: Disconnected
[01:52:24] [Server thread/INFO]: Zardexd left the game
[01:52:24] [Server thread/INFO]: Stopping singleplayer server as player logged out
[01:52:24] [Server thread/INFO]: Stopping server
[01:52:24] [Server thread/INFO]: Saving players
[01:52:24] [Server thread/INFO]: Saving worlds
```

**Comment by Waterpicker** [comment]
Forgot to close this as I added the fixed...three months ago.
