### ISSUE TITLE
[Bug]: Incompatible with VulkanMod

### ISSUE THREAD

**Issue by Nitjsefnie** [DimensionalDevelopment/DimDoors#376]
### What happened?

When DimDoors is installed alongside [VulkanMod](https://github.com/xCollateral/VulkanMod) and a dimensional door is placed down, game crashes.

### Mod Version

5.3.0

### Log

```shell
[04:35:21] [main/INFO]: Loading Minecraft 1.20.1 with Fabric Loader 0.14.25
[04:35:21] [main/INFO]: Loading 81 mods:
	- architectury 9.1.12
	- cloth-config 11.1.106
	   \-- cloth-basic-math 0.6.1
	- dimdoors 5.3.0
	   |-- cardinal-components-base 5.2.0
	   |-- cardinal-components-chunk 5.2.0
	   |-- cardinal-components-item 5.2.0
	   |-- cardinal-components-world 5.2.0
	   |-- com_flowpowered_flow-math 1.0.3
	   |-- com_github_dimensionaldevelopment_poly2tri_java 0.1.1
	   |-- mm 2.3
	   \-- org_jgrapht_jgrapht-core 1.1.0
	- fabric-api 0.91.0+1.20.1
	   |-- fabric-api-base 0.4.30+7abfd51577
	   |-- fabric-api-lookup-api-v1 1.6.35+4d8536c977
	   |-- fabric-biome-api-v1 13.0.12+215bbe9677
	   |-- fabric-block-api-v1 1.0.10+92a0d36777
	   |-- fabric-block-view-api-v2 1.0.0+92a0d36777
	   |-- fabric-blockrenderlayer-v1 1.1.40+b3afc78b77
	   |-- fabric-client-tags-api-v1 1.1.1+97bb207577
	   |-- fabric-command-api-v1 1.2.33+f71b366f77
	   |-- fabric-command-api-v2 2.2.12+b3afc78b77
	   |-- fabric-commands-v0 0.2.50+df3654b377
	   |-- fabric-containers-v0 0.1.63+df3654b377
	   |-- fabric-content-registries-v0 4.0.10+57aed33f77
	   |-- fabric-convention-tags-v1 1.5.4+a1a980da77
	   |-- fabric-crash-report-info-v1 0.2.18+aeb40ebe77
	   |-- fabric-data-generation-api-v1 12.3.3+d7b148e077
	   |-- fabric-dimensions-v1 2.1.53+8536527b77
	   |-- fabric-entity-events-v1 1.5.22+b3afc78b77
	   |-- fabric-events-interaction-v0 0.6.1+e91849a877
	   |-- fabric-events-lifecycle-v0 0.2.62+df3654b377
	   |-- fabric-game-rule-api-v1 1.0.39+ae9f657a77
	   |-- fabric-item-api-v1 2.1.27+b3afc78b77
	   |-- fabric-item-group-api-v1 4.0.11+d7b148e077
	   |-- fabric-key-binding-api-v1 1.0.36+fb8d95da77
	   |-- fabric-keybindings-v0 0.2.34+df3654b377
	   |-- fabric-lifecycle-events-v1 2.2.21+b3afc78b77
	   |-- fabric-loot-api-v2 1.2.0+96dfa95977
	   |-- fabric-loot-tables-v1 1.1.44+9e7660c677
	   |-- fabric-message-api-v1 5.1.8+d7b148e077
	   |-- fabric-mining-level-api-v1 2.1.49+b3afc78b77
	   |-- fabric-model-loading-api-v1 1.0.2+709a987177
	   |-- fabric-models-v0 0.4.1+9386d8a777
	   |-- fabric-networking-api-v1 1.3.10+eeb8eb3677
	   |-- fabric-networking-v0 0.3.50+df3654b377
	   |-- fabric-object-builder-api-v1 11.1.2+4ee0bc6077
	   |-- fabric-particles-v1 1.1.1+201a23a077
	   |-- fabric-recipe-api-v1 1.0.20+b3afc78b77
	   |-- fabric-registry-sync-v0 2.3.2+4df89eb277
	   |-- fabric-renderer-api-v1 3.2.0+39a511ba77
	   |-- fabric-renderer-indigo 1.5.0+39a511ba77
	   |-- fabric-renderer-registries-v1 3.2.45+df3654b377
	   |-- fabric-rendering-data-attachment-v1 0.3.36+92a0d36777
	   |-- fabric-rendering-fluids-v1 3.0.27+b3afc78b77
	   |-- fabric-rendering-v0 1.1.48+df3654b377
	   |-- fabric-rendering-v1 3.0.7+b3afc78b77
	   |-- fabric-resource-conditions-api-v1 2.3.7+29de845d77
	   |-- fabric-resource-loader-v0 0.11.9+132c48c177
	   |-- fabric-screen-api-v1 2.0.7+b3afc78b77
	   |-- fabric-screen-handler-api-v1 1.3.29+b3afc78b77
	   |-- fabric-sound-api-v1 1.0.12+b3afc78b77
	   |-- fabric-transfer-api-v1 3.3.3+c81d263177
	   \-- fabric-transitive-access-wideners-v1 4.3.0+6c31357e77
	- fabricloader 0.14.25
	- java 17
	- minecraft 1.20.1
	- vulkanmod 0.3.6
	   |-- org_lwjgl_lwjgl-shaderc 3.3.2
	   |-- org_lwjgl_lwjgl-shaderc_natives-linux 3.3.2
	   |-- org_lwjgl_lwjgl-shaderc_natives-macos 3.3.2
	   |-- org_lwjgl_lwjgl-shaderc_natives-macos-arm64 3.3.2
	   |-- org_lwjgl_lwjgl-shaderc_natives-windows 3.3.2
	   |-- org_lwjgl_lwjgl-vma 3.3.2
	   |-- org_lwjgl_lwjgl-vma_natives-linux 3.3.2
	   |-- org_lwjgl_lwjgl-vma_natives-macos 3.3.2
	   |-- org_lwjgl_lwjgl-vma_natives-macos-arm64 3.3.2
	   |-- org_lwjgl_lwjgl-vma_natives-windows 3.3.2
	   |-- org_lwjgl_lwjgl-vulkan 3.3.2
	   |-- org_lwjgl_lwjgl-vulkan_natives-macos 3.3.2
	   \-- org_lwjgl_lwjgl-vulkan_natives-macos-arm64 3.3.2
[04:35:21] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/Peter/Desktop/mmc-develop-win32/MultiMC/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[04:35:21] [main/INFO]: Compatibility level set to JAVA_16
[04:35:21] [main/INFO]: Compatibility level set to JAVA_17
[04:35:29] [Datafixer Bootstrap/INFO]: 188 Datafixer optimizations took 198 milliseconds
[04:35:32] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[04:35:33] [Render thread/INFO]: Setting user: Nitjsefnie
[04:35:33] [Render thread/ERROR]: No data fixer registered for monolith
[04:35:33] [Render thread/ERROR]: No data fixer registered for mask
[04:35:34] [Render thread/INFO]: Registering C2S receiver with id dimdoors:server/c5e0ff8556d73fd99e08cadf0276e74d
[04:35:34] [Render thread/INFO]: Registering S2C receiver with id dimdoors:server/c5e0ff8556d73fd99e08cadf0276e74d
[04:35:34] [Render thread/INFO]: Registering C2S receiver with id dimdoors:server/1f03bbe6451e3ab4b0f46844399676ae
[04:35:34] [Render thread/INFO]: Registering S2C receiver with id dimdoors:server/1f03bbe6451e3ab4b0f46844399676ae
[04:35:34] [Render thread/INFO]: Definitely not up to no good
[04:35:34] [Render thread/INFO]: Registering S2C receiver with id architectury:spawn_entity_packet
[04:35:34] [Render thread/INFO]: Registering C2S receiver with id dimdoors:server/a7cce38005473ab1b2cac10b76d62862
[04:35:34] [Render thread/INFO]: Registering S2C receiver with id dimdoors:server/a7cce38005473ab1b2cac10b76d62862
[04:35:34] [Render thread/INFO]: Registering C2S receiver with id dimdoors:server/dc6bb4e9d9ea3717bf2cdfce49ef6d27
[04:35:34] [Render thread/INFO]: Registering S2C receiver with id dimdoors:server/dc6bb4e9d9ea3717bf2cdfce49ef6d27
[04:35:34] [Render thread/INFO]: Registering C2S receiver with id dimdoors:server/f7b211237fa735d394a6a25fe5beebcf
[04:35:34] [Render thread/INFO]: Registering S2C receiver with id dimdoors:server/f7b211237fa735d394a6a25fe5beebcf
[04:35:34] [Render thread/INFO]: Registering C2S receiver with id dimdoors:server/255d136603ea3aca9b27642b07f65960
[04:35:34] [Render thread/INFO]: Registering S2C receiver with id dimdoors:server/255d136603ea3aca9b27642b07f65960
[04:35:34] [Render thread/INFO]: Registering C2S receiver with id dimdoors:server/eb8b09be1080365bab93fb5e47674336
[04:35:34] [Render thread/INFO]: Registering S2C receiver with id dimdoors:server/eb8b09be1080365bab93fb5e47674336
[04:35:35] [Render thread/INFO]: [Indigo] Registering Indigo renderer!
[04:35:35] [Render thread/INFO]: == VulkanMod ==
[04:35:35] [Render thread/INFO]: Selecting Platform: WIN32
[04:35:35] [Render thread/INFO]: GLFW: 3.4.0 Win32 WGL Null EGL OSMesa VisualC DLL
[04:35:35] [Render thread/INFO]: Backend library: LWJGL version 3.3.1 SNAPSHOT
[04:35:37] [Render thread/INFO]: Reloading ResourceManager: vanilla, fabric (cardinal-components-base, cardinal-components-chunk, cardinal-components-item, cardinal-components-world, cloth-config, dimdoors, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-containers-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-crash-report-info-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-events-lifecycle-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-tables-v1, fabric-message-api-v1, fabric-mining-level-api-v1, fabric-model-loading-api-v1, fabric-models-v0, fabric-networking-api-v1, fabric-networking-v0, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, mm, vulkanmod)
[04:35:37] [Worker-Main-3/INFO]: Found unifont_all_no_pua-15.0.06.hex, loading
[04:35:39] [Render thread/WARN]: Missing sound for event: minecraft:item.goat_horn.play
[04:35:39] [Render thread/WARN]: Missing sound for event: minecraft:entity.goat.screaming.horn_break
[04:35:39] [Render thread/ERROR]: Error starting SoundSystem. Turning off sounds & music
java.lang.IllegalStateException: Failed to open OpenAL device
	at net.minecraft.class_4225.method_38501(class_4225.java:283) ~[client-intermediary.jar:?]
	at net.minecraft.class_4225.method_19661(class_4225.java:153) ~[client-intermediary.jar:?]
	at net.minecraft.class_1140.method_4846(class_1140.java:116) ~[client-intermediary.jar:?]
	at net.minecraft.class_1140.method_4837(class_1140.java:106) ~[client-intermediary.jar:?]
	at net.minecraft.class_1144.method_18182(class_1144.java:125) ~[client-intermediary.jar:?]
	at net.minecraft.class_1144.method_18788(class_1144.java:40) ~[client-intermediary.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:69) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1175) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.14.25.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.25.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.25.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243) ~[NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278) ~[NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) ~[NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) ~[NewLaunch.jar:?]
[04:35:39] [Render thread/INFO]: Created: 512x1024x1 minecraft:textures/atlas/blocks.png-atlas
[04:35:40] [Render thread/INFO]: Created: 256x256x1 minecraft:textures/atlas/signs.png-atlas
[04:35:40] [Render thread/INFO]: Created: 512x512x1 minecraft:textures/atlas/shield_patterns.png-atlas
[04:35:40] [Render thread/INFO]: Created: 512x512x1 minecraft:textures/atlas/banner_patterns.png-atlas
[04:35:40] [Render thread/INFO]: Created: 1024x1024x1 minecraft:textures/atlas/armor_trims.png-atlas
[04:35:40] [Render thread/INFO]: Created: 128x64x1 minecraft:textures/atlas/decorated_pot.png-atlas
[04:35:40] [Render thread/INFO]: Created: 256x256x1 minecraft:textures/atlas/chest.png-atlas
[04:35:40] [Render thread/INFO]: Created: 512x256x1 minecraft:textures/atlas/shulker_boxes.png-atlas
[04:35:40] [Render thread/INFO]: Created: 512x256x1 minecraft:textures/atlas/beds.png-atlas
[04:35:40] [Render thread/INFO]: [STDOUT]: Blep Rare Rare Blep
[04:35:41] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[04:35:41] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[04:35:41] [Render thread/INFO]: Created: 128x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[04:35:48] [Render thread/WARN]: [fabric-registry-sync] Could not find the following registries: ae2:keytypes
[04:35:48] [Render thread/INFO]: [fabric-registry-sync] Loaded registry data [file 1/4]
[04:35:49] [Render thread/INFO]: Loaded 9 recipes
[04:35:49] [Render thread/INFO]: Loaded 1323 advancements
[04:35:57] [Render thread/INFO]: Deleting level vulkan test
[04:35:57] [Render thread/INFO]: Attempt 1...
[04:35:57] [Render thread/INFO]: Loaded 9 recipes
[04:35:57] [Render thread/INFO]: Loaded 1323 advancements
[04:36:00] [Render thread/INFO]: Loaded 9 recipes
[04:36:00] [Render thread/INFO]: Loaded 1323 advancements
[04:36:05] [Render thread/INFO]: Applied 48 biome modifications to 48 of 68 new biomes in 19.66 ms
[04:36:05] [Server thread/INFO]: Starting integrated minecraft server version 1.20.1
[04:36:05] [Server thread/INFO]: Generating keypair
[04:36:08] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[04:36:09] [Render thread/INFO]: Preparing spawn area: 0%
[04:36:09] [Render thread/INFO]: Preparing spawn area: 0%
[04:36:09] [Render thread/INFO]: Preparing spawn area: 0%
[04:36:10] [Render thread/INFO]: Preparing spawn area: 0%
[04:36:10] [Render thread/INFO]: Preparing spawn area: 2%
[04:36:11] [Render thread/INFO]: Preparing spawn area: 3%
[04:36:11] [Render thread/INFO]: Preparing spawn area: 4%
[04:36:12] [Render thread/INFO]: Preparing spawn area: 6%
[04:36:12] [Render thread/INFO]: Preparing spawn area: 8%
[04:36:13] [Render thread/INFO]: Preparing spawn area: 11%
[04:36:13] [Render thread/INFO]: Preparing spawn area: 11%
[04:36:14] [Render thread/INFO]: Preparing spawn area: 15%
[04:36:14] [Render thread/INFO]: Preparing spawn area: 18%
[04:36:15] [Render thread/INFO]: Preparing spawn area: 21%
[04:36:15] [Render thread/INFO]: Preparing spawn area: 24%
[04:36:16] [Render thread/INFO]: Preparing spawn area: 27%
[04:36:16] [Render thread/INFO]: Preparing spawn area: 30%
[04:36:17] [Render thread/INFO]: Preparing spawn area: 32%
[04:36:17] [Render thread/INFO]: Preparing spawn area: 36%
[04:36:18] [Render thread/INFO]: Preparing spawn area: 40%
[04:36:18] [Render thread/INFO]: Preparing spawn area: 43%
[04:36:19] [Render thread/INFO]: Preparing spawn area: 47%
[04:36:19] [Render thread/INFO]: Preparing spawn area: 50%
[04:36:20] [Render thread/INFO]: Preparing spawn area: 55%
[04:36:20] [Render thread/INFO]: Preparing spawn area: 58%
[04:36:21] [Render thread/INFO]: Preparing spawn area: 63%
[04:36:21] [Render thread/INFO]: Preparing spawn area: 68%
[04:36:22] [Render thread/INFO]: Preparing spawn area: 70%
[04:36:22] [Render thread/INFO]: Preparing spawn area: 74%
[04:36:23] [Render thread/INFO]: Preparing spawn area: 78%
[04:36:23] [Render thread/INFO]: Preparing spawn area: 83%
[04:36:24] [Render thread/INFO]: Preparing spawn area: 86%
[04:36:24] [Render thread/INFO]: Preparing spawn area: 91%
[04:36:25] [Render thread/INFO]: Preparing spawn area: 95%
[04:36:25] [Render thread/INFO]: Time elapsed: 16914 ms
[04:36:25] [Server thread/INFO]: Changing view distance to 16, from 10
[04:36:25] [Server thread/INFO]: Changing simulation distance to 16, from 0
[04:36:26] [Server thread/INFO]: Nitjsefnie[local:E:384d0647] logged in with entity id 165 at (-46.5, 75.0, 70.5)
[04:36:26] [Server thread/INFO]: Nitjsefnie joined the game
[04:36:26] [Render thread/WARN]: Unknown recipe category: dimdoors:shaped_tesselating/dimdoors:tesselating/world_thread_leggings
[04:36:26] [Render thread/WARN]: Unknown recipe category: dimdoors:shaped_tesselating/dimdoors:tesselating/rift_pearl
[04:36:26] [Render thread/WARN]: Unknown recipe category: dimdoors:shaped_tesselating/dimdoors:tesselating/stable_fabric
[04:36:26] [Render thread/WARN]: Unknown recipe category: dimdoors:shaped_tesselating/dimdoors:tesselating/world_thread_boots
[04:36:26] [Render thread/WARN]: Unknown recipe category: dimdoors:shaped_tesselating/dimdoors:tesselating/world_thread_chestplate
[04:36:26] [Render thread/WARN]: Unknown recipe category: dimdoors:shaped_tesselating/dimdoors:tesselating/fabric_of_finality
[04:36:26] [Render thread/WARN]: Unknown recipe category: dimdoors:shaped_tesselating/dimdoors:tesselating/liminal_lint
[04:36:26] [Render thread/WARN]: Unknown recipe category: dimdoors:shaped_tesselating/dimdoors:tesselating/fabric_of_reality
[04:36:26] [Render thread/WARN]: Unknown recipe category: dimdoors:shaped_tesselating/dimdoors:tesselating/enduring_fibers
[04:36:26] [Render thread/WARN]: Unknown recipe category: dimdoors:shapeless_tesselating/dimdoors:tesselating/rift_blade
[04:36:26] [Render thread/WARN]: Unknown recipe category: dimdoors:shaped_tesselating/dimdoors:tesselating/fuzzy_fireball
[04:36:26] [Render thread/WARN]: Unknown recipe category: dimdoors:shaped_tesselating/dimdoors:tesselating/world_thread_helmet
[04:36:26] [Render thread/WARN]: Unknown recipe category: dimdoors:shaped_tesselating/dimdoors:tesselating/reality_sponge
[04:36:27] [Render thread/INFO]: Loaded 2 advancements
[04:36:50] [Render thread/WARN]: Received passengers for unknown entity
[04:36:53] [Render thread/ERROR]: Unreported exception thrown!
java.lang.NullPointerException: Cannot invoke "net.vulkanmod.interfaces.ShaderMixed.getPipeline()" because the return value of "com.mojang.blaze3d.systems.RenderSystem.getShader()" is null
	at net.minecraft.class_286.method_43433(class_286.java:537) ~[client-intermediary.jar:?]
	at net.minecraft.class_1921.method_23012(class_1921.java:865) ~[client-intermediary.jar:?]
	at net.minecraft.class_4597$class_4598.method_22994(class_4597.java:97) ~[client-intermediary.jar:?]
	at net.minecraft.class_4597$class_4598.getBuffer(class_4597.java:46) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_22710(class_761.java:1442) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:1110) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:880) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1219) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.14.25.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.25.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.25.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243) ~[NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278) ~[NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) ~[NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) ~[NewLaunch.jar:?]
```

**Comment by Waterpicker** [comment]
Confirmed in most recent build (not released yet) that it works with VulkanMod now.
