### ISSUE TITLE
[Bug]: Game crashes when placing Eternal Fluid via bucket in glass

### ISSUE THREAD

**Issue by lexi-the-cute** [DimensionalDevelopment/DimDoors#380]
### What happened?

A bug happened!

tried placing a bucket of eternal fluid in a box surrounded by glass. game crashed

### Mod Version

5.3.0

### What versions of Minecraft does this issue happen on?

1.20.1

### Log

```shell
this happens both with sodium and the vanilla renderer. sodium mentions that it's a sprite that's null, the below is the vanilla renderer output. this is for 1.20.1


---- Minecraft Crash Report ----
// Why did you do that?

Time: 2023-12-28 17:30:27
Description: Tesselating liquid in world

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1058.method_4580(double)" because "$$121" is null
	at net.minecraft.class_775.method_3347(class_775.java:296)
	at net.fabricmc.fabric.impl.client.rendering.fluid.FluidRenderHandlerRegistryImpl.renderFluid(FluidRenderHandlerRegistryImpl.java:126)
	at net.fabricmc.fabric.api.client.render.fluid.v1.FluidRenderHandler.renderFluid(FluidRenderHandler.java:86)
	at net.minecraft.class_775.tessellateViaHandler(class_775.java:597)
	at net.minecraft.class_775.handler$eea000$fabric-rendering-fluids-v1$tesselate(class_775.java:571)
	at net.minecraft.class_775.method_3347(class_775.java)
	at net.minecraft.class_776.method_3352(class_776.java:74)
	at net.minecraft.class_846$class_851$class_4578.method_22785(class_846.java:567)
	at net.minecraft.class_846$class_851$class_4578.method_22783(class_846.java:490)
	at net.minecraft.class_846.method_22757(class_846.java:141)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```
```

**Comment by lexi-the-cute** [comment]
i decided to create a test world to demo the crashing. the block which has the eternal fluid is (0, 1, 0).

the world download is:
[2023-12-29_05-50-17_Crash.zip](https://github.com/DimensionalDevelopment/DimDoors/files/13792741/2023-12-29_05-50-17_Crash.zip)

the chunk in SNBT format is [0,0.snbt.zip](https://github.com/DimensionalDevelopment/DimDoors/files/13792748/0.0.snbt.zip)

**Comment by lexi-the-cute** [comment]
thanks!
![2023-12-30_07 20 43](https://github.com/DimensionalDevelopment/DimDoors/assets/120563837/3ced7293-1e4d-4760-9599-ecedcb5715b8)
