### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by brandonsay95** [DimensionalDevelopment/DimDoors#383]
### What happened?

dimdoors-5.3.0-forge-beta2.jar
User kicked when trying to open self placed iron dimensional door.

Edit:
The issue appears to be when a dimensional door is dropped(Itemstack ) It is probably not related to Dimensional doors.

Addional mods.

AdPother-1.20.1-8.1.3.0-build.0303.jar
aether-1.20.1-1.0.0-neoforge.jar
antiqueatlasreborn-9.2.1+item-forge-1.20.1.jar
Apotheosis-1.20.1-7.2.0.jar
ApothicAttributes-1.20.1-1.2.1.jar
Aquaculture-1.20.1-2.5.1.jar
architectury-9.1.12-forge.jar
ars_nouveau-1.20.1-4.8.3-all.jar
artifacts-forge-9.2.0.jar
balm-forge-1.20.1-7.2.1.jar
BetterHorror1[1.19.2].jar
bloodmagic-1.20.1-3.3.2-44.jar
blue_skies-1.20.1-1.3.30.jar
Bookshelf-Forge-1.20.1-20.1.8.jar
born_inchaos[Forge]1.20.1_1.1.jar
buildinggadgets2-1.0.6.jar
carryon-forge-1.20.1-2.1.2.7.jar
cc-tweaked-1.20.1-forge-1.108.4.jar
cccbridge-mc1.20.1-forge-1.6.3.jar
cloth-config-11.1.118-forge.jar
collective-1.20.1-7.30.jar
comforts-forge-6.3.4+1.20.1.jar
Controlling-forge-1.20.1-12.0.2.jar
coolcat_lib-forge-1.20.1-v1.0.2-release.jar
create-1.20.1-0.5.1.f.jar
create-stuff-additions1.20.1_v2.0.4a.jar
createaddition-1.20.1-1.2.1.jar
create_enchantment_industry-1.20.1-for-create-0.5.1.f-1.2.7.h.jar
creeperoverhaul-3.0.1-forge.jar
cristellib-1.1.5-forge.jar
curios-forge-5.4.6+1.20.1.jar
DarkUtilities-Forge-1.20.1-17.0.3.jar
dimdoors-5.3.0-forge-beta1.jar
dpanvil-1.20.1-5.0.1.jar
DungeonsArise-1.20.1-2.1.57-release.jar
dynamiclights-1.20.1.2.jar
easy_npc_1.20.1-2.0.1.jar
embersrekindled-1.20.1-1.0.3.jar
endofherobrine-1.20.1-1.0.8.2.jar
FarmersDelight-1.20.1-1.2.3.jar
FastLeafDecay-31.jar
ForgeEndertech-1.20.1-11.1.0.1-build.0289.jar
ftb-chunks-forge-2001.2.4.jar
ftb-essentials-forge-2001.2.2.jar
ftb-library-forge-2001.1.4.jar
ftb-quests-forge-2001.2.1.jar
ftb-teams-forge-2001.1.4.jar
ftb-ultimine-forge-2001.1.2.jar
GatewaysToEternity-1.20.1-4.2.3.jar
geckolib-forge-1.20.1-4.3.1.jar
interiors-0.5.2+mc1.20.1-FORGE.jar
ironchest-1.20.1-14.4.4.jar
item-filters-forge-2001.1.0-build.59.jar
Jade-1.20.1-forge-11.7.0.jar
jei-1.20.1-forge-15.2.0.27.jar
JustEnoughResources-1.20.1-1.4.0.238.jar
lootr-1.20-0.7.30.73.jar
mahoutsukai-1.20.1-v1.34.59.jar
mcjtylib-1.20-8.0.3.jar
modonomicon-1.20.1-forge-1.43.2.jar
moonlight-1.20-2.8.78-forge.jar
MouseTweaks-forge-mc1.20-2.25.jar
mutil-1.20.1-6.1.1.jar
NaturesAura-39.4.jar
notenoughwands-1.20-6.0.1.jar
occultism-1.20.1-1.99.0.jar
octolib-0.1.jar
PackingTape-1.20.1-0.14.2.jar
Patchouli-1.20.1-84-FORGE.jar
PigPen-Forge-1.20.1-15.0.2.jar
Placebo-1.20.1-8.6.0.jar
polymorph-forge-0.49.2+1.20.1.jar
ProjectFright1.20.1_0.3.2.jar
refinedstorage-1.12.4.jar
relics-1.20.1-0.5.2.1.jar
resourcefulconfig-forge-1.20.1-2.1.0.jar
Runelic-Forge-1.20.1-18.0.2.jar
Searchables-forge-1.20.1-1.0.2.jar
SmartBrainLib-forge-1.20.1-1.12.jar
sons-of-sins-1.20.1-2.1.2.jar
sophisticatedbackpacks-1.20.1-3.19.4.978.jar
sophisticatedcore-1.20.1-0.5.111.517.jar
spark-1.10.53-forge.jar
stalkercreepers-1.20.1.1.jar
starterkit-1.20.1-5.5.jar
Steam_Rails-1.5.3+forge-mc1.20.1.jar
structure_gel-1.20.1-2.16.0.jar
supplementaries-1.20-2.7.17.jar
tetra-1.20.1-6.1.0.jar
The_Undergarden-1.20.1-0.8.9.jar
tombstone-8.5.5-1.20.1.jar
Towns-and-Towers-1.12-Fabric+Forge.jar
ultimine_addition-forge-1.20.1-v1.2.0a-release.jar
walljump-1.20.1-1.1.4-forge.jar
waystones-forge-1.20-14.1.3.jar
YungsApi-1.20-Forge-4.0.2.jar
YungsBetterDesertTemples-1.20-Forge-3.0.3.jar
YungsBetterDungeons-1.20-Forge-4.0.3.jar
YungsBetterEndIsland-1.20-Forge-2.0.4.jar
YungsBetterJungleTemples-1.20-Forge-2.0.4.jar
YungsBetterMineshafts-1.20-Forge-4.0.4.jar
YungsBetterNetherFortresses-1.20-Forge-2.0.5.jar
YungsBetterOceanMonuments-1.20-Forge-3.0.4.jar
YungsBetterStrongholds-1.20-Forge-4.0.3.jar
YungsBetterWitchHuts-1.20-Forge-3.0.3.jar
YungsBridges-1.20-Forge-4.0.3.jar
YungsExtras-1.20-Forge-4.0.3.jar
YungsMenuTweaks-1.20.1-Forge-1.0.1.jar

### Log

```shell
type! org.dimdev.dimdoors.network.packet.s2c.SyncPocketAddonsS2CPacket@2045056c
[02.01 23:58:03] [Server] [Server thread/ERROR] [ne.mi.fm.lo.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/resources/language/I18n for invalid dist DEDICATED_SERVER
[02.01 23:58:03] [Server] [Server thread/ERROR] [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: Attempted to load class net/minecraft/client/resources/language/I18n for invalid dist DEDICATED_SERVER
[02.01 23:58:03] [Server] 	Index4
[02.01 23:58:03] [Server] 	Listeners:
[02.01 23:58:03] [Server] 		HIGH
[02.01 23:58:03] [Server] 		ASM: class dev.architectury.event.forge.EventHandlerImplCommon event(Lnet/minecraftforge/event/entity/player/EntityItemPickupEvent;)V
[02.01 23:58:03] [Server] 		NORMAL
[02.01 23:58:03] [Server] 		net.minecraftforge.eventbus.EventBus$$Lambda$4287/0x00007f3bc8caf0a8@772bd379
[02.01 23:58:03] [Server] 		ASM: stepsword.mahoutsukai.handlers.ServerHandler@22943be6 useItem(Lnet/minecraftforge/event/entity/player/EntityItemPickupEvent;)V
[02.01 23:58:03] [Server] 		ASM: class net.mehvahdjukaar.supplementaries.common.events.forge.ServerEventsForge onItemPickup(Lnet/minecraftforge/event/entity/player/EntityItemPickupEvent;)V
[02.01 23:58:03] [Server] 		ASM: wayoftime.bloodmagic.util.handler.event.WillHandler@7318b643 onItemPickup(Lnet/minecraftforge/event/entity/player/EntityItemPickupEvent;)V
[02.01 23:58:03] [Server] 		ASM: class com.klikli_dev.occultism.handlers.LootEventHandler giveStoneToBlacksmith(Lnet/minecraftforge/event/entity/player/EntityItemPickupEvent;)V
[02.01 23:58:03] [Server] 		ASM: Block{minecraft:air} onPickup(Lnet/minecraftforge/event/entity/player/EntityItemPickupEvent;)V
[02.01 23:58:03] [Server] 		LOWEST
[02.01 23:58:03] [Server] 		ASM: class com.hollingsworth.arsnouveau.common.event.EventHandler itemPickupEvent(Lnet/minecraftforge/event/entity/player/EntityItemPickupEvent;)V
[02.01 23:58:03] [Server] java.lang.RuntimeExceptionAttempted to load class net/minecraft/client/resources/language/I18n for invalid dist DEDICATED_SERVER
[02.01 23:58:03] [Server] 	at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.0/net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57)
[02.01 23:58:03] [Server] 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88)
[02.01 23:58:03] [Server] 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
[02.01 23:58:03] [Server] 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50)
[02.01 23:58:03] [Server] 	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113)
[02.01 23:58:03] [Server] 	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219)
[02.01 23:58:03] [Server] 	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229)
[02.01 23:58:03] [Server] 	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219)
[02.01 23:58:03] [Server] 	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135)
[02.01 23:58:03] [Server] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[02.01 23:58:03] [Server] 	at TRANSFORMER/dimdoors@5.3.0/org.dimdev.dimdoors.item.door.DimensionalDoorItemRegistrar$AutoGenDimensionalDoorItem.getName(DimensionalDoorItemRegistrar.java:161)
[02.01 23:58:03] [Server] 	at TRANSFORMER/dimdoors@5.3.0/org.dimdev.dimdoors.item.door.DimensionalDoorItemRegistrar$AutoGenDimensionalDoorItem.m_7626_(DimensionalDoorItemRegistrar.java:139)
[02.01 23:58:03] [Server] 	at TRANSFORMER/mahoutsukai@1.20.1-v1.34.59/stepsword.mahoutsukai.effects.secret.GeasEffect.hasGeas(GeasEffect.java:143)
[02.01 23:58:03] [Server] 	at TRANSFORMER/mahoutsukai@1.20.1-v1.34.59/stepsword.mahoutsukai.effects.secret.GeasEffect.geasItem(GeasEffect.java:51)
[02.01 23:58:03] [Server] 	at TRANSFORMER/mahoutsukai@1.20.1-v1.34.59/stepsword.mahoutsukai.handlers.ServerHandler.useItem(ServerHandler.java:400)
[02.01 23:58:03] [Server] 	at TRANSFORMER/mahoutsukai@1.20.1-v1.34.59/stepsword.mahoutsukai.handlers.__ServerHandler_useItem_EntityItemPickupEvent.invoke(.dynamic)
[02.01 23:58:03] [Server] 	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
[02.01 23:58:03] [Server] 	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
[02.01 23:58:03] [Server] 	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
[02.01 23:58:03] [Server] 	at TRANSFORMER/forge@47.2.0/net.minecraftforge.event.ForgeEventFactory.onItemPickup(ForgeEventFactory.java:494)
[02.01 23:58:03] [Server] 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.item.ItemEntity.m_6123_(ItemEntity.java:349)
[02.01 23:58:03] [Server] 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.player.Player.m_36277_(Player.java:560)
[02.01 23:58:03] [Server] 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.player.Player.m_8107_(Player.java:527)
[02.01 23:58:03] [Server] 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2298)
[02.01 23:58:03] [Server] 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.player.Player.m_8119_(Player.java:241)
[02.01 23:58:03] [Server] 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:467)
[02.01 23:58:03] [Server] 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:262)
[02.01 23:58:03] [Server] 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.Connection.m_129483_(Connection.java:263)
[02.01 23:58:03] [Server] 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142)
[02.01 23:58:03] [Server] 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:907)
[02.01 23:58:03] [Server] 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:283)
[02.01 23:58:03] [Server] 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814)
[02.01 23:58:03] [Server] 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661)
[02.01 23:58:03] [Server] 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251)
[02.01 23:58:03] [Server] 	at java.base/java.lang.Thread.run(Thread.java:833)
[02.01 23:58:03] [Server] [Server thread/WARN] [minecraft/ServerConnectionListener]: Failed to handle packet for /172.56.201.148:48575
[02.01 23:58:03] [Server] net.minecraft.ReportedExceptionTicking player
[02.01 23:58:03] [Server] 	at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:530) ~[server-1.20.1-20230612.114412-srg.jar%23315!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendisland.mixins.json:ServerPlayerMixin,pl:mixin:APP:dimdoors-common.mixins.json:ServerPlayerEntityMixin,pl:mixin:APP:yungsapi.mixins.json:ServerPlayerEntityTickMixin,pl:mixin:APP:betterdeserttemples.mixins.json:ServerPlayerTickMixin,pl:mixin:APP:ars_nouveau.mixins.json:camera.ANServerPlayerMixin,pl:mixin:APP:antiqueatlas-common.mixins.json:MixinPlayerEntityDeath,pl:mixin:APP:tombstone.mixins.json:ServerPlayerMixin,pl:mixin:APP:railways-common.mixins.json:conductor_possession.ServerPlayerMixin,pl:mixin:A}
[02.01 23:58:03] [Server] 	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:262) ~[server-1.20.1-20230612.114412-srg.jar%23315!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:tetra.mixins.json:ServerPlayNetHandlerMixin,pl:mixin:APP:aether.mixins.json:common.accessor.ServerGamePacketListenerImplAccessor,pl:mixin:APP:railways.mixins.json:ServerGamePacketListenerImplMixin,pl:mixin:APP:supplementaries-common.mixins.json:ServerGamePacketListenerMixin,pl:mixin:APP:mixins.artifacts.common.json:item.umbrella.server.ServerGamePacketListenerImplMixin,pl:mixin:APP:dimdoors-common.mixins.json:ExtendedServerPlayNetworkhandlerMixin,pl:mixin:APP:dimdoors-common.mixins.json:ServerPlayNetworkHandlerMixin,pl:mixin:APP:expandability-common.mixins.json:swimming.server.ServerGamePacketListenerImplMixin,pl:mixin:A}
[02.01 23:58:03] [Server] 	at net.minecraft.network.Connection.m_129483_(Connection.java:263) ~[server-1.20.1-20230612.114412-srg.jar%23315!/:?] {re:mixin,re:classloading}
[02.01 23:58:03] [Server] 	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142) ~[server-1.20.1-20230612.114412-srg.jar%23315!/:?] {re:classloading}
[02.01 23:58:03] [Server] 	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:907) ~[server-1.20.1-20230612.114412-srg.jar%23315!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
[02.01 23:58:03] [Server] 	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:283) ~[server-1.20.1-20230612.114412-srg.jar%23315!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:tombstone.mixins.json:DedicatedServerMixin,pl:mixin:A}
[02.01 23:58:03] [Server] 	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[server-1.20.1-20230612.114412-srg.jar%23315!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
[02.01 23:58:03] [Server] 	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[server-1.20.1-20230612.114412-srg.jar%23315!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
[02.01 23:58:03] [Server] 	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23315!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
[02.01 23:58:03] [Server] 	at java.lang.Thread.run(Thread.java:833) ~[?:?] {}
[02.01 23:58:03] [Server] Caused byjava.lang.RuntimeException: Attempted to load class net/minecraft/client/resources/language/I18n for invalid dist DEDICATED_SERVER
[02.01 23:58:03] [Server] 	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[fmlloader-1.20.1-47.2.0.jar%2369!/:1.{}
[02.01 23:58:03] [Server] 	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.9.jar%2355!/:?] {}
[02.01 23:58:03] [Server] 	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.9.jar%2355!/:?] {}
[02.01 23:58:03] [Server] 	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.9.jar%2355!/:?] {}
[02.01 23:58:03] [Server] 	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.10.jar:?] {}
[02.01 23:58:03] [Server] 	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {}
[02.01 23:58:03] [Server] 	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.10.jar:?] {}
[02.01 23:58:03] [Server] 	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {}
[02.01 23:58:03] [Server] 	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.10.jar:?] {}
[02.01 23:58:03] [Server] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
[02.01 23:58:03] [Server] 	at org.dimdev.dimdoors.item.door.DimensionalDoorItemRegistrar$AutoGenDimensionalDoorItem.getName(DimensionalDoorItemRegistrar.java:161) ~[dimdoors-5.3.0-forge-beta2.jar%23240!/:?] {re:classloading,pl:runtimedistcleaner:A}
[02.01 23:58:03] [Server] 	at org.dimdev.dimdoors.item.door.DimensionalDoorItemRegistrar$AutoGenDimensionalDoorItem.m_7626_(DimensionalDoorItemRegistrar.java:139) ~[dimdoors-5.3.0-forge-beta2.jar%23240!/:?] {re:classloading,pl:runtimedistcleaner:A}
[02.01 23:58:03] [Server] 	at stepsword.mahoutsukai.effects.secret.GeasEffect.hasGeas(GeasEffect.java:143) ~[mahoutsukai-1.20.1-v1.34.59.jar%23265!/:1.20.1-v1.34.{re:classloading}
[02.01 23:58:03] [Server] 	at stepsword.mahoutsukai.effects.secret.GeasEffect.geasItem(GeasEffect.java:51) ~[mahoutsukai-1.20.1-v1.34.59.jar%23265!/:1.20.1-v1.34.{re:classloading}
[02.01 23:58:03] [Server] 	at stepsword.mahoutsukai.handlers.ServerHandler.useItem(ServerHandler.java:400) ~[mahoutsukai-1.20.1-v1.34.59.jar%23265!/:1.20.1-v1.34.{re:classloading}
[02.01 23:58:03] [Server] 	at stepsword.mahoutsukai.handlers.__ServerHandler_useItem_EntityItemPickupEvent.invoke(.dynamic) ~[mahoutsukai-1.20.1-v1.34.59.jar%23265!/:1.20.1-v1.34.{re:classloading,pl:eventbus:B}
[02.01 23:58:03] [Server] 	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2352!/:?] {}
[02.01 23:58:03] [Server] 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2352!/:?] {}
[02.01 23:58:03] [Server] 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2352!/:?] {}
[02.01 23:58:03] [Server] 	at net.minecraftforge.event.ForgeEventFactory.onItemPickup(ForgeEventFactory.java:494) ~[forge-1.20.1-47.2.0-universal.jar%23320!/:?] {re:mixin,re:classloading,pl:mixin:APP:aether.mixins.json:common.ForgeEventFactoryMixin,pl:mixin:A}
[02.01 23:58:03] [Server] 	at net.minecraft.world.entity.item.ItemEntity.m_6123_(ItemEntity.java:349) ~[server-1.20.1-20230612.114412-srg.jar%23315!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:adpother:coremod,re:classloading,pl:accesstransformer:B,xf:fml:adpother:coremod}
[02.01 23:58:03] [Server] 	at net.minecraft.world.entity.player.Player.m_36277_(Player.java:560) ~[server-1.20.1-20230612.114412-srg.jar%23315!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dimdoors-common.mixins.json:PlayerEntityMixin,pl:mixin:APP:tetra.mixins.json:PlayerEntityMixin,pl:mixin:APP:blue_skies.mixins.json:PlayerEntityMixin,pl:mixin:APP:aether.mixins.json:common.PlayerMixin,pl:mixin:APP:aether.mixins.json:common.accessor.PlayerAccessor,pl:mixin:APP:darkutils.mixins.json:AccessorPlayer,pl:mixin:APP:darkutils.mixins.json:MixinPlayer,pl:mixin:APP:railways-common.mixins.json:MixinPlayer,pl:mixin:APP:railways-common.mixins.json:PlayerEntityMixin,pl:mixin:APP:carryon.mixins.json:PlayerMixin,pl:mixin:APP:supplementaries.mixins.json:PlayerProjectileMixin,pl:mixin:APP:attributeslib.mixins.json:PlayerMixin,pl:mixin:APP:tombstone.mixins.json:PlayerMixin,pl:mixin:APP:comforts.mixins.json:AccessorPlayer,pl:mixin:APP:ars_nouveau.mixins.json:elytra.ElytraPlayerMixin,pl:mixin:APP:antiqueatlas-common.mixins.json:MixinPlayerEntity,pl:mixin:APP:antiqueatlas-common.mixins.json:MixinPlayerEntityDeath,pl:mixin:APP:expandability-common.mixins.json:swimming.PlayerMixin,pl:mixin:APP:create_enchantment_industry.mixins.json:PlayerMixin,pl:mixin:A}
[02.01 23:58:03] [Server] 	at net.minecraft.world.entity.player.Player.m_8107_(Player.java:527) ~[server-1.20.1-20230612.114412-srg.jar%23315!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dimdoors-common.mixins.json:PlayerEntityMixin,pl:mixin:APP:tetra.mixins.json:PlayerEntityMixin,pl:mixin:APP:blue_skies.mixins.json:PlayerEntityMixin,pl:mixin:APP:aether.mixins.json:common.PlayerMixin,pl:mixin:APP:aether.mixins.json:common.accessor.PlayerAccessor,pl:mixin:APP:darkutils.mixins.json:AccessorPlayer,pl:mixin:APP:darkutils.mixins.json:MixinPlayer,pl:mixin:APP:railways-common.mixins.json:MixinPlayer,pl:mixin:APP:railways-common.mixins.json:PlayerEntityMixin,pl:mixin:APP:carryon.mixins.json:PlayerMixin,pl:mixin:APP:supplementaries.mixins.json:PlayerProjectileMixin,pl:mixin:APP:attributeslib.mixins.json:PlayerMixin,pl:mixin:APP:tombstone.mixins.json:PlayerMixin,pl:mixin:APP:comforts.mixins.json:AccessorPlayer,pl:mixin:APP:ars_nouveau.mixins.json:elytra.ElytraPlayerMixin,pl:mixin:APP:antiqueatlas-common.mixins.json:MixinPlayerEntity,pl:mixin:APP:antiqueatlas-common.mixins.json:MixinPlayerEntityDeath,pl:mixin:APP:expandability-common.mixins.json:swimming.PlayerMixin,pl:mixin:APP:create_enchantment_industry.mixins.json:PlayerMixin,pl:mixin:A}
[02.01 23:58:03] [Server] 	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2298) ~[server-1.20.1-20230612.114412-srg.jar%23315!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:tetra.mixins.json:LivingEntityMixin,pl:mixin:APP:blue_skies.mixins.json:LivingEntityMixin,pl:mixin:APP:aether.mixins.json:common.LivingEntityMixin,pl:mixin:APP:aether.mixins.json:common.accessor.LivingEntityAccessor,pl:mixin:APP:bookshelf.common.mixins.json:accessors.entity.AccessorLivingEntity,pl:mixin:APP:bookshelf.common.mixins.json:patches.entity.MixinLivingEntity,pl:mixin:APP:apotheosis.mixins.json:LivingEntityInvoker,pl:mixin:APP:apotheosis.mixins.json:LivingEntityMixin,pl:mixin:APP:apotheosis.mixins.json:MHFMixinLivingEntity,pl:mixin:APP:relics.mixins.json:MixinLivingEntity,pl:mixin:APP:supplementaries-common.mixins.json:LivingEntityMixin,pl:mixin:APP:curios.mixins.json:MixinLivingEntity,pl:mixin:APP:attributeslib.mixins.json:LivingEntityMixin,pl:mixin:APP:tombstone.mixins.json:LivingEntityMixin,pl:mixin:APP:mixins.artifacts.common.json:item.hurtsound.LivingEntityMixin,pl:mixin:APP:betterdeserttemples.mixins.json:PharaohKilledMixin,pl:mixin:APP:ars_nouveau.mixins.json:elytra.MixinLivingEntity,pl:mixin:APP:ars_nouveau.mixins.json:perks.PerkLivingEntity,pl:mixin:APP:ars_nouveau.mixins.json:LivingAccessor,pl:mixin:APP:expandability.mixins.json:swimming.LivingEntityMixin,pl:mixin:APP:expandability-common.mixins.json:swimming.LivingEntityMixin,pl:mixin:APP:create.mixins.json:CustomItemUseEffectsMixin,pl:mixin:APP:create.mixins.json:LavaSwimmingMixin,pl:mixin:APP:create.mixins.json:accessor.LivingEntityAccessor,pl:mixin:A}
[02.01 23:58:03] [Server] 	at net.minecraft.world.entity.player.Player.m_8119_(Player.java:241) ~[server-1.20.1-20230612.114412-srg.jar%23315!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dimdoors-common.mixins.json:PlayerEntityMixin,pl:mixin:APP:tetra.mixins.json:PlayerEntityMixin,pl:mixin:APP:blue_skies.mixins.json:PlayerEntityMixin,pl:mixin:APP:aether.mixins.json:common.PlayerMixin,pl:mixin:APP:aether.mixins.json:common.accessor.PlayerAccessor,pl:mixin:APP:darkutils.mixins.json:AccessorPlayer,pl:mixin:APP:darkutils.mixins.json:MixinPlayer,pl:mixin:APP:railways-common.mixins.json:MixinPlayer,pl:mixin:APP:railways-common.mixins.json:PlayerEntityMixin,pl:mixin:APP:carryon.mixins.json:PlayerMixin,pl:mixin:APP:supplementaries.mixins.json:PlayerProjectileMixin,pl:mixin:APP:attributeslib.mixins.json:PlayerMixin,pl:mixin:APP:tombstone.mixins.json:PlayerMixin,pl:mixin:APP:comforts.mixins.json:AccessorPlayer,pl:mixin:APP:ars_nouveau.mixins.json:elytra.ElytraPlayerMixin,pl:mixin:APP:antiqueatlas-common.mixins.json:MixinPlayerEntity,pl:mixin:APP:antiqueatlas-common.mixins.json:MixinPlayerEntityDeath,pl:mixin:APP:expandability-common.mixins.json:swimming.PlayerMixin,pl:mixin:APP:create_enchantment_industry.mixins.json:PlayerMixin,pl:mixin:A}
[02.01 23:58:03] [Server] 	at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:467) ~[server-1.20.1-20230612.114412-srg.jar%23315!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendisland.mixins.json:ServerPlayerMixin,pl:mixin:APP:dimdoors-common.mixins.json:ServerPlayerEntityMixin,pl:mixin:APP:yungsapi.mixins.json:ServerPlayerEntityTickMixin,pl:mixin:APP:betterdeserttemples.mixins.json:ServerPlayerTickMixin,pl:mixin:APP:ars_nouveau.mixins.json:camera.ANServerPlayerMixin,pl:mixin:APP:antiqueatlas-common.mixins.json:MixinPlayerEntityDeath,pl:mixin:APP:tombstone.mixins.json:ServerPlayerMixin,pl:mixin:APP:railways-common.mixins.json:conductor_possession.ServerPlayerMixin,pl:mixin:A}
```

**Comment by brandonsay95** [comment]
The issue appears to be when a dimensional door is dropped(Itemstack ) It is probably not related to Dimensional doors.
