### ISSUE TITLE
[Bug]: Server crash upon entering Limbo

### ISSUE THREAD

**Issue by GameOnne** [DimensionalDevelopment/DimDoors#389]
### What happened?

I play with my friend on a server. Whenever one of us enters Limbo, the server proceeds to shut down.
Modloader: Fabric 0.15.3
Version: 1.19.2
Mods used:
- Architectury 6.5.85
- Cloth Config 8.3.115
- Dimensional Doors 5.0.2
- Fabric API 0.77.0

### Mod Version

5.0.2

### Log

```shell
[18:34:35] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.class_148: Exception ticking world
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879) ~[server-intermediary.jar:?]
	at net.minecraft.class_3176.method_3813(class_3176.java:289) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: java.lang.NoSuchFieldError: clientRandom
	at org.dimdev.dimdoors.entity.MonolithEntity.<clinit>(MonolithEntity.java:50) ~[DimensionalDoors-5.0.2-1.19.2.jar:?]
	at net.minecraft.class_1299.method_5883(class_1299.java:487) ~[server-intermediary.jar:?]
	at net.minecraft.class_1948.method_24931(class_1948.java:355) ~[server-intermediary.jar:?]
	at net.minecraft.class_1948.method_24930(class_1948.java:284) ~[server-intermediary.jar:?]
	at net.minecraft.class_1948.method_8663(class_1948.java:212) ~[server-intermediary.jar:?]
	at net.minecraft.class_1948.method_27821(class_1948.java:200) ~[server-intermediary.jar:?]
	at net.minecraft.class_3215.method_14161(class_3215.java:376) ~[server-intermediary.jar:?]
	at net.minecraft.class_3215.method_12127(class_3215.java:323) ~[server-intermediary.jar:?]
	at net.minecraft.class_3218.method_18765(class_3218.java:319) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875) ~[server-intermediary.jar:?]
	... 5 more
[18:34:35] [Server thread/ERROR]: This crash report has been saved to: /server/./crash-reports/crash-2024-01-20_18.34.35-server.txt
```

**Comment by Qwuartzz** [comment]
I am having the exact same issue. Whenever anyone goes in Limbo the server crashes. Using all the same mods + a few others.

**Comment by Qwuartzz** [comment]
After some testing, I have found that at least my issue is something to do with the Monolith entities. Whenever they spawn, my server instantly crashes. I can enter limbo while the game is in peaceful mode because they don't spawn.

**Comment by Nyinxie** [comment]
[latest.log](https://github.com/DimensionalDevelopment/DimDoors/files/14636936/latest.log)

I can second this.

**Comment by Baughn** [comment]
It's likely caused by the 0.15.x branch of Fabric. They fixed a bug that was causing a lot of client code to be loaded on the server, which of course exposed bugs in mod code that was assuming it was running on a client.
