### ISSUE TITLE
[Bug]: game crashes when trying to render entity (1.12, 3.0.9+287)

### ISSUE THREAD

**Issue by louarn-rous** [DimensionalDevelopment/DimDoors#448]
### What happened?

while trying to make my way out of a maze, i accidentally dug out and fell to my death. upon respawning, i started to fall, seeing some red arc below me, though shortly after the game crashed with exit code 255, along with this message
```
The game crashed whilst rendering entity in world
Error: java.lang.NoSuchMethodError: net.minecraftforge.client.event.RenderLivingEvent$Pre.<init>(Lnet/minecraft/entity/EntityLivingBase;Lnet/minecraft/client/renderer/entity/RenderLivingBase;FDDD)V
```

### Mod Version

3.0.9

### Log

```shell
[19:28:30] [Server thread/INFO]: laulu_ joined the game
[19:28:32] [Server thread/INFO]: Saving and pausing game...
[19:28:32] [Server thread/INFO]: Saving chunks for level 'Survival'/overworld
[19:28:32] [main/INFO]: Loaded 159 advancements
[19:28:32] [Server thread/INFO]: Saving chunks for level 'Survival'/the_nether
[19:28:32] [Server thread/INFO]: Saving chunks for level 'Survival'/the_end
[19:28:32] [Server thread/INFO]: Saving chunks for level 'Survival'/dungeon_pockets
[19:28:32] [Server thread/INFO]: Saving chunks for level 'Survival'/dungeon_pockets
[19:28:32] [Server thread/INFO]: Saving chunks for level 'Survival'/public_pockets
[19:28:32] [Server thread/INFO]: Saving chunks for level 'Survival'/private_pockets
[19:28:32] [Server thread/INFO]: Saving chunks for level 'Survival'/limbo
[19:28:33] [Server thread/INFO]: Stopping server
[19:28:33] [Server thread/INFO]: Saving players
[19:28:33] [Server thread/INFO]: Saving worlds
[19:28:33] [Server thread/INFO]: Saving chunks for level 'Survival'/overworld
[19:28:33] [Server thread/INFO]: Saving chunks for level 'Survival'/the_nether
[19:28:33] [Server thread/INFO]: Saving chunks for level 'Survival'/the_end
[19:28:33] [Server thread/INFO]: Saving chunks for level 'Survival'/dungeon_pockets
[19:28:33] [Server thread/INFO]: Saving chunks for level 'Survival'/dungeon_pockets
[19:28:33] [Server thread/INFO]: Saving chunks for level 'Survival'/public_pockets
[19:28:33] [Server thread/INFO]: Saving chunks for level 'Survival'/private_pockets
[19:28:33] [Server thread/INFO]: Saving chunks for level 'Survival'/limbo
[19:28:34] [Server thread/INFO]: Unloading dimension 0
[19:28:34] [Server thread/INFO]: Unloading dimension -1
[19:28:34] [Server thread/INFO]: Unloading dimension 1
[19:28:34] [Server thread/INFO]: Unloading dimension 688
[19:28:34] [Server thread/INFO]: Unloading dimension 687
[19:28:34] [Server thread/INFO]: Unloading dimension 686
[19:28:34] [Server thread/INFO]: Unloading dimension 685
[19:28:34] [Server thread/INFO]: Unloading dimension 684
[19:28:35] [main/FATAL]: Reported exception thrown!
net.minecraft.util.ReportedException: Rendering entity in world
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:426) ~[bzd.class:?]
	at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:368) ~[bzd.class:?]
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:627) ~[buw.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1336) ~[buo.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1250) ~[buo.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1053) ~[buo.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117) ~[bhz.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bhz.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_202]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_202]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_202]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_202]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NoSuchMethodError: net.minecraftforge.client.event.RenderLivingEvent$Pre.<init>(Lnet/minecraft/entity/EntityLivingBase;Lnet/minecraft/client/renderer/entity/RenderLivingBase;FDDD)V
	at org.dimdev.dimdoors.client.RenderMonolith.render(RenderMonolith.java:72) ~[RenderMonolith.class:?]
	at org.dimdev.dimdoors.client.RenderMonolith.doRender(RenderMonolith.java:68) ~[RenderMonolith.class:?]
	at org.dimdev.dimdoors.client.RenderMonolith.func_76986_a(RenderMonolith.java:20) ~[RenderMonolith.class:?]
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:384) ~[bzd.class:?]
	... 14 more
[19:28:35] [main/INFO]: [net.minecraft.init.Bootstrap:func_179870_a:552]: ---- Minecraft Crash Report ----
// Quite honestly, I wouldn't worry myself about that.

Time: 10/30/24 7:28 PM
Description: Rendering entity in world

java.lang.NoSuchMethodError: net.minecraftforge.client.event.RenderLivingEvent$Pre.<init>(Lnet/minecraft/entity/EntityLivingBase;Lnet/minecraft/client/renderer/entity/RenderLivingBase;FDDD)V
	at org.dimdev.dimdoors.client.RenderMonolith.render(RenderMonolith.java:72)
	at org.dimdev.dimdoors.client.RenderMonolith.doRender(RenderMonolith.java:68)
	at org.dimdev.dimdoors.client.RenderMonolith.func_76986_a(RenderMonolith.java:20)
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:384)
	at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:368)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:627)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1336)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1250)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1053)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at org.dimdev.dimdoors.client.RenderMonolith.render(RenderMonolith.java:72)
	at org.dimdev.dimdoors.client.RenderMonolith.doRender(RenderMonolith.java:68)
	at org.dimdev.dimdoors.client.RenderMonolith.func_76986_a(RenderMonolith.java:20)

-- Entity being rendered --
Details:
	Entity Type: dimdoors:mob_monolith (org.dimdev.dimdoors.shared.entities.EntityMonolith)
	Entity ID: 321
	Entity Name: entity.monoliths.name
	Entity's Exact location: -515.50, 124.00, -506.50
	Entity's Block location: World: (-516,124,-507), Chunk: (at 12,7,5 in -33,-32; contains blocks -528,0,-512 to -513,255,-497), Region: (-2,-1; contains chunks -64,-32 to -33,-1, blocks -1024,0,-512 to -513,255,-1)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: org.dimdev.dimdoors.client.RenderMonolith@4c67d22a
	Location: -16.00,-186.80,-7.00 - World: (-16,-187,-7), Chunk: (at 0,-12,9 in -1,-1; contains blocks -16,0,-16 to -1,255,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Rotation: -33.75
	Delta: 0.5999973
Stacktrace:
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:384)
	at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:368)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:627)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1336)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1250)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['laulu_'/289, l='MpServer', x=-499.50, y=310.07, z=-499.50]]
	Chunk stats: MultiplayerChunkCache: 1369, 1369
	Level seed: 0
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (500,700,-500), Chunk: (at 4,43,12 in 31,-32; contains blocks 496,0,-512 to 511,255,-497), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 161650 game time, 226763 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 75 total; [EntityMonolith['entity.monoliths.name'/384, l='MpServer', x=-549.50, y=52.00, z=-564.50], EntityMonolith['entity.monoliths.name'/385, l='MpServer', x=-533.50, y=122.00, z=-446.50], EntityPlayerSP['laulu_'/289, l='MpServer', x=-499.50, y=310.07, z=-499.50], EntityMonolith['entity.monoliths.name'/290, l='MpServer', x=-507.50, y=124.00, z=-480.50], EntityMonolith['entity.monoliths.name'/291, l='MpServer', x=-505.50, y=125.00, z=-489.50], EntityMonolith['entity.monoliths.name'/292, l='MpServer', x=-542.50, y=50.00, z=-505.50], EntityMonolith['entity.monoliths.name'/293, l='MpServer', x=-512.50, y=124.00, z=-480.50], EntityMonolith['entity.monoliths.name'/294, l='MpServer', x=-512.50, y=124.00, z=-480.50], EntityMonolith['entity.monoliths.name'/295, l='MpServer', x=-527.50, y=124.00, z=-482.50], EntityMonolith['entity.monoliths.name'/296, l='MpServer', x=-501.50, y=119.00, z=-542.50], EntityMonolith['entity.monoliths.name'/297, l='MpServer', x=-491.50, y=86.00, z=-514.50], EntityMonolith['entity.monoliths.name'/298, l='MpServer', x=-494.50, y=86.00, z=-514.50], EntityMonolith['entity.monoliths.name'/299, l='MpServer', x=-490.50, y=86.00, z=-514.50], EntityMonolith['entity.monoliths.name'/300, l='MpServer', x=-475.50, y=51.00, z=-508.50], EntityMonolith['entity.monoliths.name'/301, l='MpServer', x=-483.50, y=44.00, z=-483.50], EntityMonolith['entity.monoliths.name'/302, l='MpServer', x=-483.50, y=44.00, z=-481.50], EntityMonolith['entity.monoliths.name'/303, l='MpServer', x=-541.50, y=37.00, z=-515.50], EntityMonolith['entity.monoliths.name'/304, l='MpServer', x=-478.50, y=119.00, z=-515.50], EntityMonolith['entity.monoliths.name'/305, l='MpServer', x=-471.50, y=44.00, z=-482.50], EntityMonolith['entity.monoliths.name'/306, l='MpServer', x=-471.50, y=44.00, z=-482.50], EntityMonolith['entity.monoliths.name'/307, l='MpServer', x=-468.50, y=44.00, z=-480.50], EntityMonolith['entity.monoliths.name'/308, l='MpServer', x=-466.50, y=44.00, z=-481.50], EntityMonolith['entity.monoliths.name'/309, l='MpServer', x=-513.50, y=99.00, z=-529.50], EntityMonolith['entity.monoliths.name'/310, l='MpServer', x=-516.50, y=99.00, z=-529.50], EntityMonolith['entity.monoliths.name'/311, l='MpServer', x=-516.50, y=99.00, z=-530.50], EntityMonolith['entity.monoliths.name'/312, l='MpServer', x=-513.50, y=99.00, z=-529.50], EntityMonolith['entity.monoliths.name'/313, l='MpServer', x=-505.50, y=36.00, z=-553.50], EntityMonolith['entity.monoliths.name'/314, l='MpServer', x=-500.50, y=36.00, z=-557.50], EntityMonolith['entity.monoliths.name'/315, l='MpServer', x=-508.50, y=54.00, z=-551.50], EntityMonolith['entity.monoliths.name'/316, l='MpServer', x=-503.50, y=54.00, z=-552.50], EntityMonolith['entity.monoliths.name'/317, l='MpServer', x=-482.50, y=46.00, z=-492.50], EntityMonolith['entity.monoliths.name'/318, l='MpServer', x=-485.50, y=46.00, z=-494.50], EntityMonolith['entity.monoliths.name'/319, l='MpServer', x=-485.50, y=46.00, z=-494.50], EntityMonolith['entity.monoliths.name'/320, l='MpServer', x=-511.50, y=124.00, z=-508.50], EntityMonolith['entity.monoliths.name'/321, l='MpServer', x=-515.50, y=124.00, z=-506.50], EntityMonolith['entity.monoliths.name'/322, l='MpServer', x=-516.50, y=124.00, z=-508.50], EntityMonolith['entity.monoliths.name'/323, l='MpServer', x=-515.50, y=124.00, z=-505.50], EntityMonolith['entity.monoliths.name'/324, l='MpServer', x=-527.50, y=33.00, z=-549.50], EntityMonolith['entity.monoliths.name'/325, l='MpServer', x=-550.50, y=35.00, z=-514.50], EntityMonolith['entity.monoliths.name'/326, l='MpServer', x=-553.50, y=35.00, z=-514.50], EntityMonolith['entity.monoliths.name'/327, l='MpServer', x=-549.50, y=35.00, z=-515.50], EntityMonolith['entity.monoliths.name'/328, l='MpServer', x=-480.50, y=44.00, z=-478.50], EntityMonolith['entity.monoliths.name'/329, l='MpServer', x=-484.50, y=44.00, z=-478.50], EntityMonolith['entity.monoliths.name'/330, l='MpServer', x=-553.50, y=7.00, z=-550.50], EntityMonolith['entity.monoliths.name'/331, l='MpServer', x=-512.50, y=124.00, z=-479.50], EntityMonolith['entity.monoliths.name'/332, l='MpServer', x=-527.50, y=124.00, z=-478.50], EntityMonolith['entity.monoliths.name'/333, l='MpServer', x=-527.50, y=124.00, z=-478.50], EntityMonolith['entity.monoliths.name'/334, l='MpServer', x=-504.50, y=123.00, z=-513.50], EntityMonolith['entity.monoliths.name'/335, l='MpServer', x=-500.50, y=123.00, z=-510.50], EntityMonolith['entity.monoliths.name'/336, l='MpServer', x=-502.50, y=123.00, z=-515.50], EntityMonolith['entity.monoliths.name'/337, l='MpServer', x=-459.50, y=83.00, z=-518.50], EntityMonolith['entity.monoliths.name'/338, l='MpServer', x=-560.50, y=7.00, z=-553.50], EntityMonolith['entity.monoliths.name'/339, l='MpServer', x=-569.50, y=101.00, z=-529.50], EntityMonolith['entity.monoliths.name'/340, l='MpServer', x=-543.50, y=29.00, z=-553.50], EntityMonolith['entity.monoliths.name'/341, l='MpServer', x=-536.50, y=102.00, z=-552.50], EntityMonolith['entity.monoliths.name'/342, l='MpServer', x=-538.50, y=102.00, z=-553.50], EntityMonolith['entity.monoliths.name'/343, l='MpServer', x=-536.50, y=102.00, z=-558.50], EntityMonolith['entity.monoliths.name'/344, l='MpServer', x=-536.50, y=102.00, z=-556.50], EntityMonolith['entity.monoliths.name'/345, l='MpServer', x=-529.50, y=124.00, z=-479.50], EntityMonolith['entity.monoliths.name'/346, l='MpServer', x=-479.50, y=45.00, z=-454.50], EntityMonolith['entity.monoliths.name'/347, l='MpServer', x=-479.50, y=45.00, z=-455.50], EntityMonolith['entity.monoliths.name'/348, l='MpServer', x=-479.50, y=45.00, z=-455.50], EntityMonolith['entity.monoliths.name'/349, l='MpServer', x=-466.50, y=66.00, z=-456.50], EntityMonolith['entity.monoliths.name'/350, l='MpServer', x=-466.50, y=66.00, z=-452.50], EntityMonolith['entity.monoliths.name'/352, l='MpServer', x=-565.50, y=101.00, z=-526.50], EntityMonolith['entity.monoliths.name'/353, l='MpServer', x=-566.50, y=101.00, z=-526.50], EntityMonolith['entity.monoliths.name'/354, l='MpServer', x=-566.50, y=101.00, z=-525.50], EntityMonolith['entity.monoliths.name'/355, l='MpServer', x=-533.50, y=122.00, z=-451.50], EntityMonolith['entity.monoliths.name'/356, l='MpServer', x=-533.50, y=122.00, z=-451.50], EntityMonolith['entity.monoliths.name'/357, l='MpServer', x=-531.50, y=122.00, z=-449.50], EntityMonolith['entity.monoliths.name'/358, l='MpServer', x=-482.50, y=45.00, z=-457.50], EntityMonolith['entity.monoliths.name'/377, l='MpServer', x=-568.50, y=124.00, z=-452.50], EntityMonolith['entity.monoliths.name'/381, l='MpServer', x=-554.50, y=52.00, z=-566.50], EntityMonolith['entity.monoliths.name'/382, l='MpServer', x=-551.50, y=52.00, z=-566.50], EntityMonolith['entity.monoliths.name'/383, l='MpServer', x=-553.50, y=52.00, z=-565.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2732)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12
	Operating System: Linux (amd64) version 6.1.11-76060111-generic
	Java Version: 1.8.0_202, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 823407312 bytes (785 MB) / 1800929280 bytes (1717 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 2 total; -Xmx4096m -Xms256m
	IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 104
	FML: MCP 9.40 Powered by Forge 14.21.1.2387 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.12} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.12-14.21.1.2387.jar) 
	UCHIJAAAA	forge{14.21.1.2387} [Minecraft Forge] (forge-1.12-14.21.1.2387.jar) 
	UCHIJAAAA	ambientsounds{2.0.0} [AmbientSounds] (AmbientSounds v2.0.8 mc1.12.jar) 
	UCHIJAAAA	biomesoplenty{7.0.0.2291} [Biomes O' Plenty] (BiomesOPlenty-1.12-7.0.0.2291-universal.jar) 
	UCHIJAAAA	dimdoors{3.0.9+287} [Dimensional Doors] (DimensionalDoors-3.0.9-287.jar) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 525.116.04' Renderer: 'NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2'
	Launched Version: forge-14.21.1.2387
	LWJGL: 2.9.4
	OpenGL: NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 525.116.04, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 12x AMD Ryzen 5 2600 Six-Core Processor
```

**Comment by TheComputerizer** [comment]
It looks like you are using a very old version of forge. Can you confirm whether this is an issue in forge `14.23.5.28.60`?
