### ISSUE TITLE
Creating linked rifts causing crash with newest build 3.0.7-b-1.247

### ISSUE THREAD

**Issue by Icebelly** [DimensionalDevelopment/DimDoors#48]
[18:36:12] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_151]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_151]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:239) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
Caused by: java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at org.poly2tri.geometry.polygon.Polygon.<clinit>(Polygon.java:17) ~[Polygon.class:?]
	at org.dimdev.ddutils.lsystem.LSystem.tesselate(LSystem.java:370) ~[LSystem.class:?]
	at org.dimdev.ddutils.lsystem.LSystem.generateLSystem(LSystem.java:89) ~[LSystem.class:?]
	at org.dimdev.ddutils.lsystem.LSystem.<clinit>(LSystem.java:31) ~[LSystem.class:?]
	at org.dimdev.dimdoors.shared.tileentities.TileEntityFloatingRift.<init>(TileEntityFloatingRift.java:46) ~[TileEntityFloatingRift.class:?]
	at org.dimdev.dimdoors.shared.blocks.BlockFloatingRift.createNewTileEntity(BlockFloatingRift.java:43) ~[BlockFloatingRift.class:?]
	at org.dimdev.dimdoors.shared.blocks.BlockFloatingRift.func_149915_a(BlockFloatingRift.java:28) ~[BlockFloatingRift.class:?]
	at net.minecraft.block.Block.createTileEntity(Block.java:1274) ~[aow.class:?]
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:623) ~[axw.class:?]
	at net.minecraft.world.World.func_180501_a(World.java:342) ~[amu.class:?]
	at net.minecraft.world.World.func_175656_a(World.java:424) ~[amu.class:?]
	at org.dimdev.dimdoors.shared.items.ItemStabilizedRiftSignature.func_180614_a(ItemStabilizedRiftSignature.java:72) ~[ItemStabilizedRiftSignature.class:?]
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:851) ~[ForgeHooks.class:?]
	at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:186) ~[aip.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:478) ~[or.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:739) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[ma.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[ma.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_151]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_151]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_151]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_151]
	at org.poly2tri.geometry.polygon.Polygon.<clinit>(Polygon.java:17) ~[Polygon.class:?]
	at org.dimdev.ddutils.lsystem.LSystem.tesselate(LSystem.java:370) ~[LSystem.class:?]
	at org.dimdev.ddutils.lsystem.LSystem.generateLSystem(LSystem.java:89) ~[LSystem.class:?]
	at org.dimdev.ddutils.lsystem.LSystem.<clinit>(LSystem.java:31) ~[LSystem.class:?]
	at org.dimdev.dimdoors.shared.tileentities.TileEntityFloatingRift.<init>(TileEntityFloatingRift.java:46) ~[TileEntityFloatingRift.class:?]
	at org.dimdev.dimdoors.shared.blocks.BlockFloatingRift.createNewTileEntity(BlockFloatingRift.java:43) ~[BlockFloatingRift.class:?]
	at org.dimdev.dimdoors.shared.blocks.BlockFloatingRift.func_149915_a(BlockFloatingRift.java:28) ~[BlockFloatingRift.class:?]
	at net.minecraft.block.Block.createTileEntity(Block.java:1274) ~[aow.class:?]
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:623) ~[axw.class:?]
	at net.minecraft.world.World.func_180501_a(World.java:342) ~[amu.class:?]
	at net.minecraft.world.World.func_175656_a(World.java:424) ~[amu.class:?]
	at org.dimdev.dimdoors.shared.items.ItemStabilizedRiftSignature.func_180614_a(ItemStabilizedRiftSignature.java:72) ~[ItemStabilizedRiftSignature.class:?]
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:851) ~[ForgeHooks.class:?]
	at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:186) ~[aip.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:478) ~[or.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:739) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[ma.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[ma.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_151]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_151]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more
[18:36:13] [Server thread/INFO] [OTG]: Pre-generating world "Biome Bundle" chunk X7 Z-10. Radius: 15 Spawned: 438/961 46% done. Elapsed: 00:01:39 ETA: 00:01:59 Mem: 32% 2657 / 8192 MB 
[18:36:14] [Server thread/INFO] [OTG]: Pre-generating world "Biome Bundle" chunk X11 Z-10. Radius: 15 Spawned: 442/961 46% done. Elapsed: 00:01:40 ETA: 00:01:58 Mem: 47% 3873 / 8192 MB 
[18:36:15] [Server thread/INFO] [OTG]: Pre-generating world "Biome Bundle" chunk X-11 Z-9. Radius: 15 Spawned: 464/961 48% done. Elapsed: 00:01:41 ETA: 00:01:49 Mem: 39% 3275 / 8192 MB 
[18:36:16] [Server thread/INFO] [OTG]: Pre-generating world "Biome Bundle" chunk X-11 Z-4. Radius: 15 Spawned: 469/961 49% done. Elapsed: 00:01:42 ETA: 00:01:48 Mem: 32% 2637 / 8192 MB 
[18:36:17] [Server thread/INFO] [OTG]: Pre-generating world "Biome Bundle" chunk X-11 Z-1. Radius: 15 Spawned: 472/961 49% done. Elapsed: 00:01:44 ETA: 00:01:48 Mem: 43% 3543 / 8192 MB 
[18:36:18] [Server thread/INFO] [OTG]: Pre-generating world "Biome Bundle" chunk X-8 Z-11. Radius: 15 Spawned: 510/961 53% done. Elapsed: 00:01:45 ETA: 00:01:33 Mem: 28% 2349 / 8192 MB 
[18:36:19] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: Could not initialize class org.dimdev.ddutils.lsystem.LSystem
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_151]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_151]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:239) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.dimdev.ddutils.lsystem.LSystem
	at org.dimdev.dimdoors.shared.tileentities.TileEntityFloatingRift.<init>(TileEntityFloatingRift.java:46) ~[TileEntityFloatingRift.class:?]
	at org.dimdev.dimdoors.shared.blocks.BlockFloatingRift.createNewTileEntity(BlockFloatingRift.java:43) ~[BlockFloatingRift.class:?]
	at org.dimdev.dimdoors.shared.blocks.BlockFloatingRift.func_149915_a(BlockFloatingRift.java:28) ~[BlockFloatingRift.class:?]
	at net.minecraft.block.Block.createTileEntity(Block.java:1274) ~[aow.class:?]
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:623) ~[axw.class:?]
	at net.minecraft.world.World.func_180501_a(World.java:342) ~[amu.class:?]
	at net.minecraft.world.World.func_175656_a(World.java:424) ~[amu.class:?]
	at org.dimdev.dimdoors.shared.items.ItemStabilizedRiftSignature.func_180614_a(ItemStabilizedRiftSignature.java:79) ~[ItemStabilizedRiftSignature.class:?]
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:851) ~[ForgeHooks.class:?]
	at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:186) ~[aip.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:478) ~[or.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:739) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[ma.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[ma.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_151]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_151]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more
[18:36:19] [main/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: Could not initialize class org.dimdev.ddutils.lsystem.LSystem
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_151]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_151]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1086) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:162) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:53) [NewLaunch.jar:?]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.dimdev.ddutils.lsystem.LSystem
	at org.dimdev.dimdoors.shared.tileentities.TileEntityFloatingRift.<init>(TileEntityFloatingRift.java:46) ~[TileEntityFloatingRift.class:?]
	at org.dimdev.dimdoors.shared.blocks.BlockFloatingRift.createNewTileEntity(BlockFloatingRift.java:43) ~[BlockFloatingRift.class:?]
	at org.dimdev.dimdoors.shared.blocks.BlockFloatingRift.func_149915_a(BlockFloatingRift.java:28) ~[BlockFloatingRift.class:?]
	at net.minecraft.block.Block.createTileEntity(Block.java:1274) ~[aow.class:?]
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:623) ~[axw.class:?]
	at net.minecraft.world.World.func_180501_a(World.java:342) ~[amu.class:?]
	at net.minecraft.client.multiplayer.WorldClient.func_180503_b(WorldClient.java:366) ~[bsb.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.func_147234_a(NetHandlerPlayClient.java:774) ~[brz.class:?]
	at net.minecraft.network.play.server.SPacketBlockChange.func_148833_a(SourceFile:40) ~[ij.class:?]
	at net.minecraft.network.play.server.SPacketBlockChange.func_148833_a(SourceFile:13) ~[ij.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_151]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_151]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 17 more

**Comment by Robijnvogel** [comment]
@Runemoro is Minecraft, perchance, including a higher version of `slf4j` than we are including [via gradle](https://github.com/DimensionalDevelopment/DimDoors/blob/1.12-WIP/build.gradle#L81)? Because our version certainly isn't the latest.

Also, we aren't actually calling `slf4j` anywhere in our code, so why is it in our `build.gradle` at all?

**Comment by Runemoro** [comment]
@Robijnvogel It's included because poly2tri depends on it (which doesn't use gradle, so we have to manually add its dependencies).

**Comment by Runemoro** [comment]
The library is in the jar, and a search for `slf4j` returns nothing in the Minecraft code.

**Comment by Runemoro** [comment]
Fixed.
