### ISSUE TITLE
Limbo and tomb many graves

### ISSUE THREAD

**Issue by mkire** [DimensionalDevelopment/DimDoors#74]
whenever i fall out of a dimension i die, and the game crashes. when i reload i'm in limbo and all my stuff is gone, presumably because Tomb grabbed it all for the grave

Description: Exception in server tick loop
java.lang.IllegalStateException: Entry was removed
	at java.util.IdentityHashMap$EntryIterator$Entry.checkIndexForEntryUse(Unknown Source)
	at java.util.IdentityHashMap$EntryIterator$Entry.getValue(Unknown Source)
	at net.ilexiconn.llibrary.server.ServerEventHandler.onServerTickEvent(ServerEventHandler.java:161)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1891_ServerEventHandler_onServerTickEvent_ServerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:265)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:712)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

**Comment by Runemoro** [comment]
This seems to be caused by LLibrary, not Dimensional Doors.
